/* Generated by re2c 0.16 on Wed May 24 11:51:41 2017 */
#line 1 "../Source/raw_parser.h"
#include "parser.h"
#include <iostream>
#include <vector>
#include "parser_helper.h"
#include "PBRT/TextureParams.h"
#include "system.h"

#define API_MODUL(func) auto name = getString(cursor,end); ParamSet set; initParamSet(set, cursor,end); \
						scene.func(name,set);

#line 11 "../Source/raw_parser.h"


void parse(const std::unique_ptr<char[]>& data, size_t length, PbrtScene& scene, std::string directory, const std::string& filename)
{
	System::setDirectory(directory);
	// special case for --nodirhierarchy
	directory = System::getCurrentDirectory();

	const char* cursor = data.get();
	const char* const end = data.get() + length;
	const char* marker = nullptr;
	System::runtimeInfo("parsing " + filename);
	System::runtimeInfo("removing comments");
	// remove comments
	{
		bool isComment = false;
		bool isString = false;
		char* c = data.get();
		while (c < end)
		{
			if(isComment)
			{
				if (*c == '\n')
					isComment = false;
				else
					*c = ' ';
			}
			else if(*c == '#' && !isString)
			{
				isComment = true;
				*c = ' ';
			}
			else if(*c == '"')
			{
				// dont comment out # in strings ("map #3")
				isString = !isString;
			}
			c++;
		}
	}
	System::runtimeInfo("parsing commands");
	try
	{
		while (cursor < end && *cursor)
		{
			marker = nullptr;
			
#line 62 "<stdout>"
{
	char yych;
	unsigned int yyaccept = 0;
	yych = *cursor;
	switch (yych) {
	case '#':	goto yy4;
	case 'A':	goto yy6;
	case 'C':	goto yy7;
	case 'F':	goto yy8;
	case 'I':	goto yy9;
	case 'L':	goto yy10;
	case 'M':	goto yy11;
	case 'N':	goto yy12;
	case 'O':	goto yy13;
	case 'P':	goto yy14;
	case 'R':	goto yy15;
	case 'S':	goto yy16;
	case 'T':	goto yy17;
	case 'V':	goto yy18;
	case 'W':	goto yy19;
	default:	goto yy2;
	}
yy2:
	++cursor;
yy3:
#line 65 "../Source/raw_parser.h"
	{													continue; }
#line 90 "<stdout>"
yy4:
	++cursor;
#line 66 "../Source/raw_parser.h"
	{ while(*cursor && *cursor != '\n') cursor++;		continue; }
#line 95 "<stdout>"
yy6:
	yyaccept = 0;
	yych = *(marker = ++cursor);
	switch (yych) {
	case 'c':	goto yy20;
	case 'r':	goto yy22;
	case 't':	goto yy23;
	default:	goto yy3;
	}
yy7:
	yyaccept = 0;
	yych = *(marker = ++cursor);
	switch (yych) {
	case 'a':	goto yy24;
	case 'o':	goto yy25;
	default:	goto yy3;
	}
yy8:
	yyaccept = 0;
	yych = *(marker = ++cursor);
	switch (yych) {
	case 'i':	goto yy26;
	default:	goto yy3;
	}
yy9:
	yyaccept = 0;
	yych = *(marker = ++cursor);
	switch (yych) {
	case 'd':	goto yy27;
	case 'n':	goto yy28;
	default:	goto yy3;
	}
yy10:
	yyaccept = 0;
	yych = *(marker = ++cursor);
	switch (yych) {
	case 'i':	goto yy29;
	case 'o':	goto yy30;
	default:	goto yy3;
	}
yy11:
	yyaccept = 0;
	yych = *(marker = ++cursor);
	switch (yych) {
	case 'a':	goto yy31;
	default:	goto yy3;
	}
yy12:
	yyaccept = 0;
	yych = *(marker = ++cursor);
	switch (yych) {
	case 'a':	goto yy32;
	default:	goto yy3;
	}
yy13:
	yyaccept = 0;
	yych = *(marker = ++cursor);
	switch (yych) {
	case 'b':	goto yy33;
	default:	goto yy3;
	}
yy14:
	yyaccept = 0;
	yych = *(marker = ++cursor);
	switch (yych) {
	case 'i':	goto yy34;
	default:	goto yy3;
	}
yy15:
	yyaccept = 0;
	yych = *(marker = ++cursor);
	switch (yych) {
	case 'e':	goto yy35;
	case 'o':	goto yy36;
	default:	goto yy3;
	}
yy16:
	yyaccept = 0;
	yych = *(marker = ++cursor);
	switch (yych) {
	case 'a':	goto yy37;
	case 'c':	goto yy38;
	case 'h':	goto yy39;
	case 'u':	goto yy40;
	default:	goto yy3;
	}
yy17:
	yyaccept = 0;
	yych = *(marker = ++cursor);
	switch (yych) {
	case 'e':	goto yy41;
	case 'r':	goto yy42;
	default:	goto yy3;
	}
yy18:
	yyaccept = 0;
	yych = *(marker = ++cursor);
	switch (yych) {
	case 'o':	goto yy43;
	default:	goto yy3;
	}
yy19:
	yyaccept = 0;
	yych = *(marker = ++cursor);
	switch (yych) {
	case 'o':	goto yy44;
	default:	goto yy3;
	}
yy20:
	yych = *++cursor;
	switch (yych) {
	case 'c':	goto yy45;
	case 't':	goto yy46;
	default:	goto yy21;
	}
yy21:
	cursor = marker;
	switch (yyaccept) {
	case 0: 	goto yy3;
	case 1: 	goto yy160;
	default:	goto yy239;
	}
yy22:
	yych = *++cursor;
	switch (yych) {
	case 'e':	goto yy47;
	default:	goto yy21;
	}
yy23:
	yych = *++cursor;
	switch (yych) {
	case 't':	goto yy48;
	default:	goto yy21;
	}
yy24:
	yych = *++cursor;
	switch (yych) {
	case 'm':	goto yy49;
	default:	goto yy21;
	}
yy25:
	yych = *++cursor;
	switch (yych) {
	case 'n':	goto yy50;
	case 'o':	goto yy51;
	default:	goto yy21;
	}
yy26:
	yych = *++cursor;
	switch (yych) {
	case 'l':	goto yy52;
	default:	goto yy21;
	}
yy27:
	yych = *++cursor;
	switch (yych) {
	case 'e':	goto yy53;
	default:	goto yy21;
	}
yy28:
	yych = *++cursor;
	switch (yych) {
	case 'c':	goto yy54;
	default:	goto yy21;
	}
yy29:
	yych = *++cursor;
	switch (yych) {
	case 'g':	goto yy55;
	default:	goto yy21;
	}
yy30:
	yych = *++cursor;
	switch (yych) {
	case 'o':	goto yy56;
	default:	goto yy21;
	}
yy31:
	yych = *++cursor;
	switch (yych) {
	case 'k':	goto yy57;
	case 't':	goto yy58;
	default:	goto yy21;
	}
yy32:
	yych = *++cursor;
	switch (yych) {
	case 'm':	goto yy59;
	default:	goto yy21;
	}
yy33:
	yych = *++cursor;
	switch (yych) {
	case 'j':	goto yy60;
	default:	goto yy21;
	}
yy34:
	yych = *++cursor;
	switch (yych) {
	case 'x':	goto yy61;
	default:	goto yy21;
	}
yy35:
	yych = *++cursor;
	switch (yych) {
	case 'n':	goto yy62;
	case 'v':	goto yy63;
	default:	goto yy21;
	}
yy36:
	yych = *++cursor;
	switch (yych) {
	case 't':	goto yy64;
	default:	goto yy21;
	}
yy37:
	yych = *++cursor;
	switch (yych) {
	case 'm':	goto yy65;
	default:	goto yy21;
	}
yy38:
	yych = *++cursor;
	switch (yych) {
	case 'a':	goto yy66;
	default:	goto yy21;
	}
yy39:
	yych = *++cursor;
	switch (yych) {
	case 'a':	goto yy67;
	default:	goto yy21;
	}
yy40:
	yych = *++cursor;
	switch (yych) {
	case 'r':	goto yy68;
	default:	goto yy21;
	}
yy41:
	yych = *++cursor;
	switch (yych) {
	case 'x':	goto yy69;
	default:	goto yy21;
	}
yy42:
	yych = *++cursor;
	switch (yych) {
	case 'a':	goto yy70;
	default:	goto yy21;
	}
yy43:
	yych = *++cursor;
	switch (yych) {
	case 'l':	goto yy71;
	default:	goto yy21;
	}
yy44:
	yych = *++cursor;
	switch (yych) {
	case 'r':	goto yy72;
	default:	goto yy21;
	}
yy45:
	yych = *++cursor;
	switch (yych) {
	case 'e':	goto yy73;
	default:	goto yy21;
	}
yy46:
	yych = *++cursor;
	switch (yych) {
	case 'i':	goto yy74;
	default:	goto yy21;
	}
yy47:
	yych = *++cursor;
	switch (yych) {
	case 'a':	goto yy75;
	default:	goto yy21;
	}
yy48:
	yych = *++cursor;
	switch (yych) {
	case 'r':	goto yy76;
	default:	goto yy21;
	}
yy49:
	yych = *++cursor;
	switch (yych) {
	case 'e':	goto yy77;
	default:	goto yy21;
	}
yy50:
	yych = *++cursor;
	switch (yych) {
	case 'c':	goto yy78;
	default:	goto yy21;
	}
yy51:
	yych = *++cursor;
	switch (yych) {
	case 'r':	goto yy79;
	default:	goto yy21;
	}
yy52:
	yych = *++cursor;
	switch (yych) {
	case 'm':	goto yy80;
	default:	goto yy21;
	}
yy53:
	yych = *++cursor;
	switch (yych) {
	case 'n':	goto yy82;
	default:	goto yy21;
	}
yy54:
	yych = *++cursor;
	switch (yych) {
	case 'l':	goto yy83;
	default:	goto yy21;
	}
yy55:
	yych = *++cursor;
	switch (yych) {
	case 'h':	goto yy84;
	default:	goto yy21;
	}
yy56:
	yych = *++cursor;
	switch (yych) {
	case 'k':	goto yy85;
	default:	goto yy21;
	}
yy57:
	yych = *++cursor;
	switch (yych) {
	case 'e':	goto yy86;
	default:	goto yy21;
	}
yy58:
	yych = *++cursor;
	switch (yych) {
	case 'e':	goto yy87;
	default:	goto yy21;
	}
yy59:
	yych = *++cursor;
	switch (yych) {
	case 'e':	goto yy88;
	default:	goto yy21;
	}
yy60:
	yych = *++cursor;
	switch (yych) {
	case 'e':	goto yy89;
	default:	goto yy21;
	}
yy61:
	yych = *++cursor;
	switch (yych) {
	case 'e':	goto yy90;
	default:	goto yy21;
	}
yy62:
	yych = *++cursor;
	switch (yych) {
	case 'd':	goto yy91;
	default:	goto yy21;
	}
yy63:
	yych = *++cursor;
	switch (yych) {
	case 'e':	goto yy92;
	default:	goto yy21;
	}
yy64:
	yych = *++cursor;
	switch (yych) {
	case 'a':	goto yy93;
	default:	goto yy21;
	}
yy65:
	yych = *++cursor;
	switch (yych) {
	case 'p':	goto yy94;
	default:	goto yy21;
	}
yy66:
	yych = *++cursor;
	switch (yych) {
	case 'l':	goto yy95;
	default:	goto yy21;
	}
yy67:
	yych = *++cursor;
	switch (yych) {
	case 'p':	goto yy96;
	default:	goto yy21;
	}
yy68:
	yych = *++cursor;
	switch (yych) {
	case 'f':	goto yy97;
	default:	goto yy21;
	}
yy69:
	yych = *++cursor;
	switch (yych) {
	case 't':	goto yy98;
	default:	goto yy21;
	}
yy70:
	yych = *++cursor;
	switch (yych) {
	case 'n':	goto yy99;
	default:	goto yy21;
	}
yy71:
	yych = *++cursor;
	switch (yych) {
	case 'u':	goto yy100;
	default:	goto yy21;
	}
yy72:
	yych = *++cursor;
	switch (yych) {
	case 'l':	goto yy101;
	default:	goto yy21;
	}
yy73:
	yych = *++cursor;
	switch (yych) {
	case 'l':	goto yy102;
	default:	goto yy21;
	}
yy74:
	yych = *++cursor;
	switch (yych) {
	case 'v':	goto yy103;
	default:	goto yy21;
	}
yy75:
	yych = *++cursor;
	switch (yych) {
	case 'L':	goto yy104;
	default:	goto yy21;
	}
yy76:
	yych = *++cursor;
	switch (yych) {
	case 'i':	goto yy105;
	default:	goto yy21;
	}
yy77:
	yych = *++cursor;
	switch (yych) {
	case 'r':	goto yy106;
	default:	goto yy21;
	}
yy78:
	yych = *++cursor;
	switch (yych) {
	case 'a':	goto yy107;
	default:	goto yy21;
	}
yy79:
	yych = *++cursor;
	switch (yych) {
	case 'd':	goto yy108;
	default:	goto yy21;
	}
yy80:
	++cursor;
#line 90 "../Source/raw_parser.h"
	{ API_MODUL(apiFilm);				continue; }
#line 573 "<stdout>"
yy82:
	yych = *++cursor;
	switch (yych) {
	case 't':	goto yy109;
	default:	goto yy21;
	}
yy83:
	yych = *++cursor;
	switch (yych) {
	case 'u':	goto yy110;
	default:	goto yy21;
	}
yy84:
	yych = *++cursor;
	switch (yych) {
	case 't':	goto yy111;
	default:	goto yy21;
	}
yy85:
	yych = *++cursor;
	switch (yych) {
	case 'A':	goto yy112;
	default:	goto yy21;
	}
yy86:
	yych = *++cursor;
	switch (yych) {
	case 'N':	goto yy113;
	default:	goto yy21;
	}
yy87:
	yych = *++cursor;
	switch (yych) {
	case 'r':	goto yy114;
	default:	goto yy21;
	}
yy88:
	yych = *++cursor;
	switch (yych) {
	case 'd':	goto yy115;
	default:	goto yy21;
	}
yy89:
	yych = *++cursor;
	switch (yych) {
	case 'c':	goto yy116;
	default:	goto yy21;
	}
yy90:
	yych = *++cursor;
	switch (yych) {
	case 'l':	goto yy117;
	default:	goto yy21;
	}
yy91:
	yych = *++cursor;
	switch (yych) {
	case 'e':	goto yy118;
	default:	goto yy21;
	}
yy92:
	yych = *++cursor;
	switch (yych) {
	case 'r':	goto yy119;
	default:	goto yy21;
	}
yy93:
	yych = *++cursor;
	switch (yych) {
	case 't':	goto yy120;
	default:	goto yy21;
	}
yy94:
	yych = *++cursor;
	switch (yych) {
	case 'l':	goto yy121;
	default:	goto yy21;
	}
yy95:
	yych = *++cursor;
	switch (yych) {
	case 'e':	goto yy122;
	default:	goto yy21;
	}
yy96:
	yych = *++cursor;
	switch (yych) {
	case 'e':	goto yy124;
	default:	goto yy21;
	}
yy97:
	yych = *++cursor;
	switch (yych) {
	case 'a':	goto yy126;
	default:	goto yy21;
	}
yy98:
	yych = *++cursor;
	switch (yych) {
	case 'u':	goto yy127;
	default:	goto yy21;
	}
yy99:
	yych = *++cursor;
	switch (yych) {
	case 's':	goto yy128;
	default:	goto yy21;
	}
yy100:
	yych = *++cursor;
	switch (yych) {
	case 'm':	goto yy129;
	default:	goto yy21;
	}
yy101:
	yych = *++cursor;
	switch (yych) {
	case 'd':	goto yy130;
	default:	goto yy21;
	}
yy102:
	yych = *++cursor;
	switch (yych) {
	case 'e':	goto yy131;
	default:	goto yy21;
	}
yy103:
	yych = *++cursor;
	switch (yych) {
	case 'e':	goto yy132;
	default:	goto yy21;
	}
yy104:
	yych = *++cursor;
	switch (yych) {
	case 'i':	goto yy133;
	default:	goto yy21;
	}
yy105:
	yych = *++cursor;
	switch (yych) {
	case 'b':	goto yy134;
	default:	goto yy21;
	}
yy106:
	yych = *++cursor;
	switch (yych) {
	case 'a':	goto yy135;
	default:	goto yy21;
	}
yy107:
	yych = *++cursor;
	switch (yych) {
	case 't':	goto yy137;
	default:	goto yy21;
	}
yy108:
	yych = *++cursor;
	switch (yych) {
	case 'S':	goto yy138;
	case 'i':	goto yy139;
	default:	goto yy21;
	}
yy109:
	yych = *++cursor;
	switch (yych) {
	case 'i':	goto yy140;
	default:	goto yy21;
	}
yy110:
	yych = *++cursor;
	switch (yych) {
	case 'd':	goto yy141;
	default:	goto yy21;
	}
yy111:
	yych = *++cursor;
	switch (yych) {
	case 'S':	goto yy142;
	default:	goto yy21;
	}
yy112:
	yych = *++cursor;
	switch (yych) {
	case 't':	goto yy143;
	default:	goto yy21;
	}
yy113:
	yych = *++cursor;
	switch (yych) {
	case 'a':	goto yy145;
	default:	goto yy21;
	}
yy114:
	yych = *++cursor;
	switch (yych) {
	case 'i':	goto yy146;
	default:	goto yy21;
	}
yy115:
	yych = *++cursor;
	switch (yych) {
	case 'M':	goto yy147;
	default:	goto yy21;
	}
yy116:
	yych = *++cursor;
	switch (yych) {
	case 't':	goto yy148;
	default:	goto yy21;
	}
yy117:
	yych = *++cursor;
	switch (yych) {
	case 'F':	goto yy149;
	default:	goto yy21;
	}
yy118:
	yych = *++cursor;
	switch (yych) {
	case 'r':	goto yy150;
	default:	goto yy21;
	}
yy119:
	yych = *++cursor;
	switch (yych) {
	case 's':	goto yy151;
	default:	goto yy21;
	}
yy120:
	yych = *++cursor;
	switch (yych) {
	case 'e':	goto yy152;
	default:	goto yy21;
	}
yy121:
	yych = *++cursor;
	switch (yych) {
	case 'e':	goto yy154;
	default:	goto yy21;
	}
yy122:
	++cursor;
#line 70 "../Source/raw_parser.h"
	{ scene.apiScale(getFloats(3,cursor,end));	continue; }
#line 819 "<stdout>"
yy124:
	++cursor;
#line 97 "../Source/raw_parser.h"
	{ API_MODUL(apiShape);				continue; }
#line 824 "<stdout>"
yy126:
	yych = *++cursor;
	switch (yych) {
	case 'c':	goto yy155;
	default:	goto yy21;
	}
yy127:
	yych = *++cursor;
	switch (yych) {
	case 'r':	goto yy156;
	default:	goto yy21;
	}
yy128:
	yych = *++cursor;
	switch (yych) {
	case 'f':	goto yy157;
	case 'l':	goto yy158;
	default:	goto yy21;
	}
yy129:
	yych = *++cursor;
	switch (yych) {
	case 'e':	goto yy159;
	default:	goto yy21;
	}
yy130:
	yych = *++cursor;
	switch (yych) {
	case 'B':	goto yy161;
	case 'E':	goto yy162;
	default:	goto yy21;
	}
yy131:
	yych = *++cursor;
	switch (yych) {
	case 'r':	goto yy163;
	default:	goto yy21;
	}
yy132:
	yych = *++cursor;
	switch (yych) {
	case 'T':	goto yy164;
	default:	goto yy21;
	}
yy133:
	yych = *++cursor;
	switch (yych) {
	case 'g':	goto yy165;
	default:	goto yy21;
	}
yy134:
	yych = *++cursor;
	switch (yych) {
	case 'u':	goto yy166;
	default:	goto yy21;
	}
yy135:
	++cursor;
#line 88 "../Source/raw_parser.h"
	{ API_MODUL(apiCamera);				continue; }
#line 885 "<stdout>"
yy137:
	yych = *++cursor;
	switch (yych) {
	case 'T':	goto yy167;
	default:	goto yy21;
	}
yy138:
	yych = *++cursor;
	switch (yych) {
	case 'y':	goto yy168;
	default:	goto yy21;
	}
yy139:
	yych = *++cursor;
	switch (yych) {
	case 'n':	goto yy169;
	default:	goto yy21;
	}
yy140:
	yych = *++cursor;
	switch (yych) {
	case 't':	goto yy170;
	default:	goto yy21;
	}
yy141:
	yych = *++cursor;
	switch (yych) {
	case 'e':	goto yy171;
	default:	goto yy21;
	}
yy142:
	yych = *++cursor;
	switch (yych) {
	case 'o':	goto yy173;
	default:	goto yy21;
	}
yy143:
	++cursor;
#line 72 "../Source/raw_parser.h"
	{ scene.apiLookAt(getFloats(9,cursor,end));	continue; }
#line 926 "<stdout>"
yy145:
	yych = *++cursor;
	switch (yych) {
	case 'm':	goto yy174;
	default:	goto yy21;
	}
yy146:
	yych = *++cursor;
	switch (yych) {
	case 'a':	goto yy175;
	default:	goto yy21;
	}
yy147:
	yych = *++cursor;
	switch (yych) {
	case 'a':	goto yy176;
	default:	goto yy21;
	}
yy148:
	yych = *++cursor;
	switch (yych) {
	case 'B':	goto yy177;
	case 'E':	goto yy178;
	case 'I':	goto yy179;
	default:	goto yy21;
	}
yy149:
	yych = *++cursor;
	switch (yych) {
	case 'i':	goto yy180;
	default:	goto yy21;
	}
yy150:
	yych = *++cursor;
	switch (yych) {
	case 'e':	goto yy181;
	default:	goto yy21;
	}
yy151:
	yych = *++cursor;
	switch (yych) {
	case 'e':	goto yy182;
	default:	goto yy21;
	}
yy152:
	++cursor;
#line 71 "../Source/raw_parser.h"
	{ scene.apiRotate(getFloats(4,cursor,end));	continue; }
#line 975 "<stdout>"
yy154:
	yych = *++cursor;
	switch (yych) {
	case 'r':	goto yy183;
	default:	goto yy21;
	}
yy155:
	yych = *++cursor;
	switch (yych) {
	case 'e':	goto yy185;
	default:	goto yy21;
	}
yy156:
	yych = *++cursor;
	switch (yych) {
	case 'e':	goto yy186;
	default:	goto yy21;
	}
yy157:
	yych = *++cursor;
	switch (yych) {
	case 'o':	goto yy188;
	default:	goto yy21;
	}
yy158:
	yych = *++cursor;
	switch (yych) {
	case 'a':	goto yy189;
	default:	goto yy21;
	}
yy159:
	yyaccept = 1;
	yych = *(marker = ++cursor);
	switch (yych) {
	case 'I':	goto yy190;
	default:	goto yy160;
	}
yy160:
#line 107 "../Source/raw_parser.h"
	{ API_MODUL(apiVolume);				continue; }
#line 1016 "<stdout>"
yy161:
	yych = *++cursor;
	switch (yych) {
	case 'e':	goto yy191;
	default:	goto yy21;
	}
yy162:
	yych = *++cursor;
	switch (yych) {
	case 'n':	goto yy192;
	default:	goto yy21;
	}
yy163:
	yych = *++cursor;
	switch (yych) {
	case 'a':	goto yy193;
	default:	goto yy21;
	}
yy164:
	yych = *++cursor;
	switch (yych) {
	case 'r':	goto yy194;
	default:	goto yy21;
	}
yy165:
	yych = *++cursor;
	switch (yych) {
	case 'h':	goto yy195;
	default:	goto yy21;
	}
yy166:
	yych = *++cursor;
	switch (yych) {
	case 't':	goto yy196;
	default:	goto yy21;
	}
yy167:
	yych = *++cursor;
	switch (yych) {
	case 'r':	goto yy197;
	default:	goto yy21;
	}
yy168:
	yych = *++cursor;
	switch (yych) {
	case 's':	goto yy198;
	default:	goto yy21;
	}
yy169:
	yych = *++cursor;
	switch (yych) {
	case 'a':	goto yy199;
	default:	goto yy21;
	}
yy170:
	yych = *++cursor;
	switch (yych) {
	case 'y':	goto yy200;
	default:	goto yy21;
	}
yy171:
	++cursor;
#line 117 "../Source/raw_parser.h"
	{	
									auto filename = getString(cursor, end);
									parseFile(filename,scene,directory); 
									System::setDirectory(directory);
									continue; 	
								}
#line 1086 "<stdout>"
yy173:
	yych = *++cursor;
	switch (yych) {
	case 'u':	goto yy202;
	default:	goto yy21;
	}
yy174:
	yych = *++cursor;
	switch (yych) {
	case 'e':	goto yy203;
	default:	goto yy21;
	}
yy175:
	yych = *++cursor;
	switch (yych) {
	case 'l':	goto yy204;
	default:	goto yy21;
	}
yy176:
	yych = *++cursor;
	switch (yych) {
	case 't':	goto yy206;
	default:	goto yy21;
	}
yy177:
	yych = *++cursor;
	switch (yych) {
	case 'e':	goto yy207;
	default:	goto yy21;
	}
yy178:
	yych = *++cursor;
	switch (yych) {
	case 'n':	goto yy208;
	default:	goto yy21;
	}
yy179:
	yych = *++cursor;
	switch (yych) {
	case 'n':	goto yy209;
	default:	goto yy21;
	}
yy180:
	yych = *++cursor;
	switch (yych) {
	case 'l':	goto yy210;
	default:	goto yy21;
	}
yy181:
	yych = *++cursor;
	switch (yych) {
	case 'r':	goto yy211;
	default:	goto yy21;
	}
yy182:
	yych = *++cursor;
	switch (yych) {
	case 'O':	goto yy213;
	default:	goto yy21;
	}
yy183:
	++cursor;
#line 89 "../Source/raw_parser.h"
	{ API_MODUL(apiSampler);			continue; }
#line 1151 "<stdout>"
yy185:
	yych = *++cursor;
	switch (yych) {
	case 'I':	goto yy214;
	default:	goto yy21;
	}
yy186:
	++cursor;
#line 108 "../Source/raw_parser.h"
	{
									auto name = getString(cursor,end);
									auto type = getString(cursor,end);
									auto clas = getString(cursor,end);
									ParamSet set; initParamSet(set, cursor,end);
									scene.apiTexture(name,type,clas,set);
									continue;
								}
#line 1169 "<stdout>"
yy188:
	yych = *++cursor;
	switch (yych) {
	case 'r':	goto yy215;
	default:	goto yy21;
	}
yy189:
	yych = *++cursor;
	switch (yych) {
	case 't':	goto yy216;
	default:	goto yy21;
	}
yy190:
	yych = *++cursor;
	switch (yych) {
	case 'n':	goto yy217;
	default:	goto yy21;
	}
yy191:
	yych = *++cursor;
	switch (yych) {
	case 'g':	goto yy218;
	default:	goto yy21;
	}
yy192:
	yych = *++cursor;
	switch (yych) {
	case 'd':	goto yy219;
	default:	goto yy21;
	}
yy193:
	yych = *++cursor;
	switch (yych) {
	case 't':	goto yy221;
	default:	goto yy21;
	}
yy194:
	yych = *++cursor;
	switch (yych) {
	case 'a':	goto yy222;
	default:	goto yy21;
	}
yy195:
	yych = *++cursor;
	switch (yych) {
	case 't':	goto yy223;
	default:	goto yy21;
	}
yy196:
	yych = *++cursor;
	switch (yych) {
	case 'e':	goto yy224;
	default:	goto yy21;
	}
yy197:
	yych = *++cursor;
	switch (yych) {
	case 'a':	goto yy225;
	default:	goto yy21;
	}
yy198:
	yych = *++cursor;
	switch (yych) {
	case 'T':	goto yy226;
	default:	goto yy21;
	}
yy199:
	yych = *++cursor;
	switch (yych) {
	case 't':	goto yy227;
	default:	goto yy21;
	}
yy200:
	++cursor;
#line 68 "../Source/raw_parser.h"
	{ scene.apiIdentity();						continue; }
#line 1246 "<stdout>"
yy202:
	yych = *++cursor;
	switch (yych) {
	case 'r':	goto yy228;
	default:	goto yy21;
	}
yy203:
	yych = *++cursor;
	switch (yych) {
	case 'd':	goto yy229;
	default:	goto yy21;
	}
yy204:
	++cursor;
#line 104 "../Source/raw_parser.h"
	{ API_MODUL(apiMaterial);			continue; }
#line 1263 "<stdout>"
yy206:
	yych = *++cursor;
	switch (yych) {
	case 'e':	goto yy230;
	default:	goto yy21;
	}
yy207:
	yych = *++cursor;
	switch (yych) {
	case 'g':	goto yy231;
	default:	goto yy21;
	}
yy208:
	yych = *++cursor;
	switch (yych) {
	case 'd':	goto yy232;
	default:	goto yy21;
	}
yy209:
	yych = *++cursor;
	switch (yych) {
	case 's':	goto yy234;
	default:	goto yy21;
	}
yy210:
	yych = *++cursor;
	switch (yych) {
	case 't':	goto yy235;
	default:	goto yy21;
	}
yy211:
	++cursor;
#line 91 "../Source/raw_parser.h"
	{ API_MODUL(apiRenderer);			continue; }
#line 1298 "<stdout>"
yy213:
	yych = *++cursor;
	switch (yych) {
	case 'r':	goto yy236;
	default:	goto yy21;
	}
yy214:
	yych = *++cursor;
	switch (yych) {
	case 'n':	goto yy237;
	default:	goto yy21;
	}
yy215:
	yych = *++cursor;
	switch (yych) {
	case 'm':	goto yy238;
	default:	goto yy21;
	}
yy216:
	yych = *++cursor;
	switch (yych) {
	case 'e':	goto yy240;
	default:	goto yy21;
	}
yy217:
	yych = *++cursor;
	switch (yych) {
	case 't':	goto yy242;
	default:	goto yy21;
	}
yy218:
	yych = *++cursor;
	switch (yych) {
	case 'i':	goto yy243;
	default:	goto yy21;
	}
yy219:
	++cursor;
#line 86 "../Source/raw_parser.h"
	{ scene.apiWorldEnd();				break; }
#line 1339 "<stdout>"
yy221:
	yych = *++cursor;
	switch (yych) {
	case 'o':	goto yy244;
	default:	goto yy21;
	}
yy222:
	yych = *++cursor;
	switch (yych) {
	case 'n':	goto yy245;
	default:	goto yy21;
	}
yy223:
	yych = *++cursor;
	switch (yych) {
	case 'S':	goto yy246;
	default:	goto yy21;
	}
yy224:
	yych = *++cursor;
	switch (yych) {
	case 'B':	goto yy247;
	case 'E':	goto yy248;
	default:	goto yy21;
	}
yy225:
	yych = *++cursor;
	switch (yych) {
	case 'n':	goto yy249;
	default:	goto yy21;
	}
yy226:
	yych = *++cursor;
	switch (yych) {
	case 'r':	goto yy250;
	default:	goto yy21;
	}
yy227:
	yych = *++cursor;
	switch (yych) {
	case 'e':	goto yy251;
	default:	goto yy21;
	}
yy228:
	yych = *++cursor;
	switch (yych) {
	case 'c':	goto yy252;
	default:	goto yy21;
	}
yy229:
	yych = *++cursor;
	switch (yych) {
	case 'M':	goto yy253;
	default:	goto yy21;
	}
yy230:
	yych = *++cursor;
	switch (yych) {
	case 'r':	goto yy254;
	default:	goto yy21;
	}
yy231:
	yych = *++cursor;
	switch (yych) {
	case 'i':	goto yy255;
	default:	goto yy21;
	}
yy232:
	++cursor;
#line 99 "../Source/raw_parser.h"
	{ scene.apiObjectEnd();				continue; }
#line 1411 "<stdout>"
yy234:
	yych = *++cursor;
	switch (yych) {
	case 't':	goto yy256;
	default:	goto yy21;
	}
yy235:
	yych = *++cursor;
	switch (yych) {
	case 'e':	goto yy257;
	default:	goto yy21;
	}
yy236:
	yych = *++cursor;
	switch (yych) {
	case 'i':	goto yy258;
	default:	goto yy21;
	}
yy237:
	yych = *++cursor;
	switch (yych) {
	case 't':	goto yy259;
	default:	goto yy21;
	}
yy238:
	yyaccept = 2;
	yych = *(marker = ++cursor);
	switch (yych) {
	case 'B':	goto yy260;
	case 'E':	goto yy261;
	default:	goto yy239;
	}
yy239:
#line 73 "../Source/raw_parser.h"
	{ scene.apiTransform(getFloats(4 * 4,cursor,end));		continue; }
#line 1447 "<stdout>"
yy240:
	++cursor;
#line 69 "../Source/raw_parser.h"
	{ scene.apiTranslate(getFloats(3,cursor,end));		continue; }
#line 1452 "<stdout>"
yy242:
	yych = *++cursor;
	switch (yych) {
	case 'e':	goto yy262;
	default:	goto yy21;
	}
yy243:
	yych = *++cursor;
	switch (yych) {
	case 'n':	goto yy263;
	default:	goto yy21;
	}
yy244:
	yych = *++cursor;
	switch (yych) {
	case 'r':	goto yy265;
	default:	goto yy21;
	}
yy245:
	yych = *++cursor;
	switch (yych) {
	case 's':	goto yy267;
	default:	goto yy21;
	}
yy246:
	yych = *++cursor;
	switch (yych) {
	case 'o':	goto yy268;
	default:	goto yy21;
	}
yy247:
	yych = *++cursor;
	switch (yych) {
	case 'e':	goto yy269;
	default:	goto yy21;
	}
yy248:
	yych = *++cursor;
	switch (yych) {
	case 'n':	goto yy270;
	default:	goto yy21;
	}
yy249:
	yych = *++cursor;
	switch (yych) {
	case 's':	goto yy271;
	default:	goto yy21;
	}
yy250:
	yych = *++cursor;
	switch (yych) {
	case 'a':	goto yy272;
	default:	goto yy21;
	}
yy251:
	yych = *++cursor;
	switch (yych) {
	case 'S':	goto yy273;
	default:	goto yy21;
	}
yy252:
	yych = *++cursor;
	switch (yych) {
	case 'e':	goto yy274;
	default:	goto yy21;
	}
yy253:
	yych = *++cursor;
	switch (yych) {
	case 'a':	goto yy276;
	default:	goto yy21;
	}
yy254:
	yych = *++cursor;
	switch (yych) {
	case 'i':	goto yy277;
	default:	goto yy21;
	}
yy255:
	yych = *++cursor;
	switch (yych) {
	case 'n':	goto yy278;
	default:	goto yy21;
	}
yy256:
	yych = *++cursor;
	switch (yych) {
	case 'a':	goto yy280;
	default:	goto yy21;
	}
yy257:
	yych = *++cursor;
	switch (yych) {
	case 'r':	goto yy281;
	default:	goto yy21;
	}
yy258:
	yych = *++cursor;
	switch (yych) {
	case 'e':	goto yy283;
	default:	goto yy21;
	}
yy259:
	yych = *++cursor;
	switch (yych) {
	case 'e':	goto yy284;
	default:	goto yy21;
	}
yy260:
	yych = *++cursor;
	switch (yych) {
	case 'e':	goto yy285;
	default:	goto yy21;
	}
yy261:
	yych = *++cursor;
	switch (yych) {
	case 'n':	goto yy286;
	default:	goto yy21;
	}
yy262:
	yych = *++cursor;
	switch (yych) {
	case 'g':	goto yy287;
	default:	goto yy21;
	}
yy263:
	++cursor;
#line 85 "../Source/raw_parser.h"
	{ scene.apiWorldBegin();			continue; }
#line 1583 "<stdout>"
yy265:
	++cursor;
#line 94 "../Source/raw_parser.h"
	{ API_MODUL(apiAccelerator);		continue; }
#line 1588 "<stdout>"
yy267:
	yych = *++cursor;
	switch (yych) {
	case 'f':	goto yy288;
	default:	goto yy21;
	}
yy268:
	yych = *++cursor;
	switch (yych) {
	case 'u':	goto yy289;
	default:	goto yy21;
	}
yy269:
	yych = *++cursor;
	switch (yych) {
	case 'g':	goto yy290;
	default:	goto yy21;
	}
yy270:
	yych = *++cursor;
	switch (yych) {
	case 'd':	goto yy291;
	default:	goto yy21;
	}
yy271:
	yych = *++cursor;
	switch (yych) {
	case 'f':	goto yy293;
	default:	goto yy21;
	}
yy272:
	yych = *++cursor;
	switch (yych) {
	case 'n':	goto yy294;
	default:	goto yy21;
	}
yy273:
	yych = *++cursor;
	switch (yych) {
	case 'y':	goto yy295;
	default:	goto yy21;
	}
yy274:
	++cursor;
#line 101 "../Source/raw_parser.h"
	{ API_MODUL(apiLightSource);		continue; }
#line 1635 "<stdout>"
yy276:
	yych = *++cursor;
	switch (yych) {
	case 't':	goto yy296;
	default:	goto yy21;
	}
yy277:
	yych = *++cursor;
	switch (yych) {
	case 'a':	goto yy297;
	default:	goto yy21;
	}
yy278:
	++cursor;
#line 98 "../Source/raw_parser.h"
	{ scene.apiObjectBegin(getString(cursor,end)); continue; }
#line 1652 "<stdout>"
yy280:
	yych = *++cursor;
	switch (yych) {
	case 'n':	goto yy298;
	default:	goto yy21;
	}
yy281:
	++cursor;
#line 95 "../Source/raw_parser.h"
	{ API_MODUL(apiPixelFilter);		continue; }
#line 1663 "<stdout>"
yy283:
	yych = *++cursor;
	switch (yych) {
	case 'n':	goto yy299;
	default:	goto yy21;
	}
yy284:
	yych = *++cursor;
	switch (yych) {
	case 'g':	goto yy300;
	default:	goto yy21;
	}
yy285:
	yych = *++cursor;
	switch (yych) {
	case 'g':	goto yy301;
	default:	goto yy21;
	}
yy286:
	yych = *++cursor;
	switch (yych) {
	case 'd':	goto yy302;
	default:	goto yy21;
	}
yy287:
	yych = *++cursor;
	switch (yych) {
	case 'r':	goto yy304;
	default:	goto yy21;
	}
yy288:
	yych = *++cursor;
	switch (yych) {
	case 'o':	goto yy305;
	default:	goto yy21;
	}
yy289:
	yych = *++cursor;
	switch (yych) {
	case 'r':	goto yy306;
	default:	goto yy21;
	}
yy290:
	yych = *++cursor;
	switch (yych) {
	case 'i':	goto yy307;
	default:	goto yy21;
	}
yy291:
	++cursor;
#line 82 "../Source/raw_parser.h"
	{ scene.apiAttributeEnd();			continue; }
#line 1716 "<stdout>"
yy293:
	yych = *++cursor;
	switch (yych) {
	case 'o':	goto yy308;
	default:	goto yy21;
	}
yy294:
	yych = *++cursor;
	switch (yych) {
	case 's':	goto yy309;
	default:	goto yy21;
	}
yy295:
	yych = *++cursor;
	switch (yych) {
	case 's':	goto yy310;
	default:	goto yy21;
	}
yy296:
	yych = *++cursor;
	switch (yych) {
	case 'e':	goto yy311;
	default:	goto yy21;
	}
yy297:
	yych = *++cursor;
	switch (yych) {
	case 'l':	goto yy312;
	default:	goto yy21;
	}
yy298:
	yych = *++cursor;
	switch (yych) {
	case 'c':	goto yy314;
	default:	goto yy21;
	}
yy299:
	yych = *++cursor;
	switch (yych) {
	case 't':	goto yy315;
	default:	goto yy21;
	}
yy300:
	yych = *++cursor;
	switch (yych) {
	case 'r':	goto yy316;
	default:	goto yy21;
	}
yy301:
	yych = *++cursor;
	switch (yych) {
	case 'i':	goto yy317;
	default:	goto yy21;
	}
yy302:
	++cursor;
#line 84 "../Source/raw_parser.h"
	{ scene.apiTransformEnd();			continue; }
#line 1775 "<stdout>"
yy304:
	yych = *++cursor;
	switch (yych) {
	case 'a':	goto yy318;
	default:	goto yy21;
	}
yy305:
	yych = *++cursor;
	switch (yych) {
	case 'r':	goto yy319;
	default:	goto yy21;
	}
yy306:
	yych = *++cursor;
	switch (yych) {
	case 'c':	goto yy320;
	default:	goto yy21;
	}
yy307:
	yych = *++cursor;
	switch (yych) {
	case 'n':	goto yy321;
	default:	goto yy21;
	}
yy308:
	yych = *++cursor;
	switch (yych) {
	case 'r':	goto yy323;
	default:	goto yy21;
	}
yy309:
	yych = *++cursor;
	switch (yych) {
	case 'f':	goto yy324;
	default:	goto yy21;
	}
yy310:
	yych = *++cursor;
	switch (yych) {
	case 't':	goto yy325;
	default:	goto yy21;
	}
yy311:
	yych = *++cursor;
	switch (yych) {
	case 'r':	goto yy326;
	default:	goto yy21;
	}
yy312:
	++cursor;
#line 106 "../Source/raw_parser.h"
	{ scene.apiNamedMaterial(getString(cursor,end)); continue; }
#line 1828 "<stdout>"
yy314:
	yych = *++cursor;
	switch (yych) {
	case 'e':	goto yy327;
	default:	goto yy21;
	}
yy315:
	yych = *++cursor;
	switch (yych) {
	case 'a':	goto yy329;
	default:	goto yy21;
	}
yy316:
	yych = *++cursor;
	switch (yych) {
	case 'a':	goto yy330;
	default:	goto yy21;
	}
yy317:
	yych = *++cursor;
	switch (yych) {
	case 'n':	goto yy331;
	default:	goto yy21;
	}
yy318:
	yych = *++cursor;
	switch (yych) {
	case 't':	goto yy333;
	default:	goto yy21;
	}
yy319:
	yych = *++cursor;
	switch (yych) {
	case 'm':	goto yy334;
	default:	goto yy21;
	}
yy320:
	yych = *++cursor;
	switch (yych) {
	case 'e':	goto yy335;
	default:	goto yy21;
	}
yy321:
	++cursor;
#line 81 "../Source/raw_parser.h"
	{ scene.apiAttributeBegin();		continue; }
#line 1875 "<stdout>"
yy323:
	yych = *++cursor;
	switch (yych) {
	case 'm':	goto yy337;
	default:	goto yy21;
	}
yy324:
	yych = *++cursor;
	switch (yych) {
	case 'o':	goto yy339;
	default:	goto yy21;
	}
yy325:
	yych = *++cursor;
	switch (yych) {
	case 'e':	goto yy340;
	default:	goto yy21;
	}
yy326:
	yych = *++cursor;
	switch (yych) {
	case 'i':	goto yy341;
	default:	goto yy21;
	}
yy327:
	++cursor;
#line 100 "../Source/raw_parser.h"
	{ scene.apiObjectInstance(getString(cursor,end)); continue; }
#line 1904 "<stdout>"
yy329:
	yych = *++cursor;
	switch (yych) {
	case 't':	goto yy342;
	default:	goto yy21;
	}
yy330:
	yych = *++cursor;
	switch (yych) {
	case 't':	goto yy343;
	default:	goto yy21;
	}
yy331:
	++cursor;
#line 83 "../Source/raw_parser.h"
	{ scene.apiTransformBegin();		continue; }
#line 1921 "<stdout>"
yy333:
	yych = *++cursor;
	switch (yych) {
	case 'o':	goto yy344;
	default:	goto yy21;
	}
yy334:
	yych = *++cursor;
	switch (yych) {
	case ' ':	goto yy345;
	default:	goto yy21;
	}
yy335:
	++cursor;
#line 102 "../Source/raw_parser.h"
	{ API_MODUL(apiAreaLightSource);	continue; }
#line 1938 "<stdout>"
yy337:
	++cursor;
#line 74 "../Source/raw_parser.h"
	{ scene.apiConcatTransfrom(getFloats(4 * 4,cursor,end));	continue; }
#line 1943 "<stdout>"
yy339:
	yych = *++cursor;
	switch (yych) {
	case 'r':	goto yy346;
	default:	goto yy21;
	}
yy340:
	yych = *++cursor;
	switch (yych) {
	case 'm':	goto yy347;
	default:	goto yy21;
	}
yy341:
	yych = *++cursor;
	switch (yych) {
	case 'a':	goto yy349;
	default:	goto yy21;
	}
yy342:
	yych = *++cursor;
	switch (yych) {
	case 'i':	goto yy350;
	default:	goto yy21;
	}
yy343:
	yych = *++cursor;
	switch (yych) {
	case 'o':	goto yy351;
	default:	goto yy21;
	}
yy344:
	yych = *++cursor;
	switch (yych) {
	case 'r':	goto yy352;
	default:	goto yy21;
	}
yy345:
	yych = *++cursor;
	switch (yych) {
	case 'A':	goto yy354;
	case 'E':	goto yy355;
	case 'S':	goto yy356;
	default:	goto yy21;
	}
yy346:
	yych = *++cursor;
	switch (yych) {
	case 'm':	goto yy357;
	default:	goto yy21;
	}
yy347:
	++cursor;
#line 78 "../Source/raw_parser.h"
	{ scene.apiCoordinateSystem(getString(cursor,end));	continue; }
#line 1998 "<stdout>"
yy349:
	yych = *++cursor;
	switch (yych) {
	case 'l':	goto yy359;
	default:	goto yy21;
	}
yy350:
	yych = *++cursor;
	switch (yych) {
	case 'o':	goto yy361;
	default:	goto yy21;
	}
yy351:
	yych = *++cursor;
	switch (yych) {
	case 'r':	goto yy362;
	default:	goto yy21;
	}
yy352:
	++cursor;
#line 93 "../Source/raw_parser.h"
	{ API_MODUL(apiVolumeIntegrator);	continue; }
#line 2021 "<stdout>"
yy354:
	yych = *++cursor;
	switch (yych) {
	case 'l':	goto yy364;
	default:	goto yy21;
	}
yy355:
	yych = *++cursor;
	switch (yych) {
	case 'n':	goto yy365;
	default:	goto yy21;
	}
yy356:
	yych = *++cursor;
	switch (yych) {
	case 't':	goto yy366;
	default:	goto yy21;
	}
yy357:
	++cursor;
#line 79 "../Source/raw_parser.h"
	{ scene.apiCoordSysTransform(getString(cursor,end)); continue;}
#line 2044 "<stdout>"
yy359:
	++cursor;
#line 105 "../Source/raw_parser.h"
	{ API_MODUL(apiMakeNamedMaterial);	continue; }
#line 2049 "<stdout>"
yy361:
	yych = *++cursor;
	switch (yych) {
	case 'n':	goto yy367;
	default:	goto yy21;
	}
yy362:
	++cursor;
#line 92 "../Source/raw_parser.h"
	{ API_MODUL(apiSurfaceIntegrator);	continue; }
#line 2060 "<stdout>"
yy364:
	yych = *++cursor;
	switch (yych) {
	case 'l':	goto yy369;
	default:	goto yy21;
	}
yy365:
	yych = *++cursor;
	switch (yych) {
	case 'd':	goto yy371;
	default:	goto yy21;
	}
yy366:
	yych = *++cursor;
	switch (yych) {
	case 'a':	goto yy372;
	default:	goto yy21;
	}
yy367:
	++cursor;
#line 103 "../Source/raw_parser.h"
	{ scene.apiReverseOrientation();	continue; }
#line 2083 "<stdout>"
yy369:
	++cursor;
#line 77 "../Source/raw_parser.h"
	{ scene.apiSetActiveTransform(true);		continue; }
#line 2088 "<stdout>"
yy371:
	yych = *++cursor;
	switch (yych) {
	case 'T':	goto yy373;
	default:	goto yy21;
	}
yy372:
	yych = *++cursor;
	switch (yych) {
	case 'r':	goto yy374;
	default:	goto yy21;
	}
yy373:
	yych = *++cursor;
	switch (yych) {
	case 'i':	goto yy375;
	default:	goto yy21;
	}
yy374:
	yych = *++cursor;
	switch (yych) {
	case 't':	goto yy376;
	default:	goto yy21;
	}
yy375:
	yych = *++cursor;
	switch (yych) {
	case 'm':	goto yy377;
	default:	goto yy21;
	}
yy376:
	yych = *++cursor;
	switch (yych) {
	case 'T':	goto yy378;
	default:	goto yy21;
	}
yy377:
	yych = *++cursor;
	switch (yych) {
	case 'e':	goto yy379;
	default:	goto yy21;
	}
yy378:
	yych = *++cursor;
	switch (yych) {
	case 'i':	goto yy381;
	default:	goto yy21;
	}
yy379:
	++cursor;
#line 76 "../Source/raw_parser.h"
	{ scene.apiSetActiveTransform(false);		continue; }
#line 2141 "<stdout>"
yy381:
	yych = *++cursor;
	switch (yych) {
	case 'm':	goto yy382;
	default:	goto yy21;
	}
yy382:
	yych = *++cursor;
	switch (yych) {
	case 'e':	goto yy383;
	default:	goto yy21;
	}
yy383:
	++cursor;
#line 75 "../Source/raw_parser.h"
	{ scene.apiSetActiveTransform(true);	continue; }
#line 2158 "<stdout>"
}
#line 124 "../Source/raw_parser.h"

		}
	}
	catch(const ParserException& e)
	{
		// determine line
		size_t line = 1;
		const char* cur = data.get();
		while (cur < e.where()) { if (*cur == '\n')++line;++cur; }
		System::error("line: " + std::to_string(line) + " : " + std::string(e.what()) + " in file: " + filename);
	}
	catch(const std::exception& e)
	{
		// determine line
		size_t line = 1;
		const char* cur = data.get();
		while (cur < cursor) { if (*cur == '\n')++line; ++cur; }
		System::error("line: " + std::to_string(line) + " : " + std::string(e.what()) + " in file: " + filename);
	}
}

pbrtParamType getParamTypeFromString(const std::string& s)
{
	const char* cursor = &(*s.begin());
	const char* end = cursor + s.length();
	const char* marker = nullptr;
	
#line 2188 "<stdout>"
{
	char yych;
	yych = *cursor;
	switch (yych) {
	case 'b':	goto yy389;
	case 'c':	goto yy390;
	case 'f':	goto yy391;
	case 'i':	goto yy392;
	case 'n':	goto yy393;
	case 'p':	goto yy394;
	case 'r':	goto yy395;
	case 's':	goto yy396;
	case 't':	goto yy397;
	case 'v':	goto yy398;
	case 'x':	goto yy399;
	default:	goto yy387;
	}
yy387:
	++cursor;
yy388:
#line 156 "../Source/raw_parser.h"
	{return pbrtParamType::ERROR;}
#line 2211 "<stdout>"
yy389:
	yych = *(marker = ++cursor);
	switch (yych) {
	case 'l':	goto yy400;
	case 'o':	goto yy402;
	default:	goto yy388;
	}
yy390:
	yych = *(marker = ++cursor);
	switch (yych) {
	case 'o':	goto yy403;
	default:	goto yy388;
	}
yy391:
	yych = *(marker = ++cursor);
	switch (yych) {
	case 'l':	goto yy404;
	default:	goto yy388;
	}
yy392:
	yych = *(marker = ++cursor);
	switch (yych) {
	case 'n':	goto yy405;
	default:	goto yy388;
	}
yy393:
	yych = *(marker = ++cursor);
	switch (yych) {
	case 'o':	goto yy406;
	default:	goto yy388;
	}
yy394:
	yych = *(marker = ++cursor);
	switch (yych) {
	case 'o':	goto yy407;
	default:	goto yy388;
	}
yy395:
	yych = *(marker = ++cursor);
	switch (yych) {
	case 'g':	goto yy408;
	default:	goto yy388;
	}
yy396:
	yych = *(marker = ++cursor);
	switch (yych) {
	case 'p':	goto yy409;
	case 't':	goto yy410;
	default:	goto yy388;
	}
yy397:
	yych = *(marker = ++cursor);
	switch (yych) {
	case 'e':	goto yy411;
	default:	goto yy388;
	}
yy398:
	yych = *(marker = ++cursor);
	switch (yych) {
	case 'e':	goto yy412;
	default:	goto yy388;
	}
yy399:
	yych = *(marker = ++cursor);
	switch (yych) {
	case 'y':	goto yy413;
	default:	goto yy388;
	}
yy400:
	yych = *++cursor;
	switch (yych) {
	case 'a':	goto yy414;
	default:	goto yy401;
	}
yy401:
	cursor = marker;
	goto yy388;
yy402:
	yych = *++cursor;
	switch (yych) {
	case 'o':	goto yy415;
	default:	goto yy401;
	}
yy403:
	yych = *++cursor;
	switch (yych) {
	case 'l':	goto yy416;
	default:	goto yy401;
	}
yy404:
	yych = *++cursor;
	switch (yych) {
	case 'o':	goto yy417;
	default:	goto yy401;
	}
yy405:
	yych = *++cursor;
	switch (yych) {
	case 't':	goto yy418;
	default:	goto yy401;
	}
yy406:
	yych = *++cursor;
	switch (yych) {
	case 'r':	goto yy419;
	default:	goto yy401;
	}
yy407:
	yych = *++cursor;
	switch (yych) {
	case 'i':	goto yy420;
	default:	goto yy401;
	}
yy408:
	yych = *++cursor;
	switch (yych) {
	case 'b':	goto yy421;
	default:	goto yy401;
	}
yy409:
	yych = *++cursor;
	switch (yych) {
	case 'e':	goto yy423;
	default:	goto yy401;
	}
yy410:
	yych = *++cursor;
	switch (yych) {
	case 'r':	goto yy424;
	default:	goto yy401;
	}
yy411:
	yych = *++cursor;
	switch (yych) {
	case 'x':	goto yy425;
	default:	goto yy401;
	}
yy412:
	yych = *++cursor;
	switch (yych) {
	case 'c':	goto yy426;
	default:	goto yy401;
	}
yy413:
	yych = *++cursor;
	switch (yych) {
	case 'z':	goto yy427;
	default:	goto yy401;
	}
yy414:
	yych = *++cursor;
	switch (yych) {
	case 'c':	goto yy429;
	default:	goto yy401;
	}
yy415:
	yych = *++cursor;
	switch (yych) {
	case 'l':	goto yy430;
	default:	goto yy401;
	}
yy416:
	yych = *++cursor;
	switch (yych) {
	case 'o':	goto yy432;
	default:	goto yy401;
	}
yy417:
	yych = *++cursor;
	switch (yych) {
	case 'a':	goto yy433;
	default:	goto yy401;
	}
yy418:
	yych = *++cursor;
	switch (yych) {
	case 'e':	goto yy434;
	default:	goto yy401;
	}
yy419:
	yych = *++cursor;
	switch (yych) {
	case 'm':	goto yy435;
	default:	goto yy401;
	}
yy420:
	yych = *++cursor;
	switch (yych) {
	case 'n':	goto yy436;
	default:	goto yy401;
	}
yy421:
	++cursor;
#line 166 "../Source/raw_parser.h"
	{return pbrtParamType::RGB; }
#line 2407 "<stdout>"
yy423:
	yych = *++cursor;
	switch (yych) {
	case 'c':	goto yy437;
	default:	goto yy401;
	}
yy424:
	yych = *++cursor;
	switch (yych) {
	case 'i':	goto yy438;
	default:	goto yy401;
	}
yy425:
	yych = *++cursor;
	switch (yych) {
	case 't':	goto yy439;
	default:	goto yy401;
	}
yy426:
	yych = *++cursor;
	switch (yych) {
	case 't':	goto yy440;
	default:	goto yy401;
	}
yy427:
	++cursor;
#line 167 "../Source/raw_parser.h"
	{return pbrtParamType::XYZ; }
#line 2436 "<stdout>"
yy429:
	yych = *++cursor;
	switch (yych) {
	case 'k':	goto yy441;
	default:	goto yy401;
	}
yy430:
	++cursor;
#line 159 "../Source/raw_parser.h"
	{return pbrtParamType::Bool; }
#line 2447 "<stdout>"
yy432:
	yych = *++cursor;
	switch (yych) {
	case 'r':	goto yy442;
	default:	goto yy401;
	}
yy433:
	yych = *++cursor;
	switch (yych) {
	case 't':	goto yy444;
	default:	goto yy401;
	}
yy434:
	yych = *++cursor;
	switch (yych) {
	case 'g':	goto yy446;
	default:	goto yy401;
	}
yy435:
	yych = *++cursor;
	switch (yych) {
	case 'a':	goto yy447;
	default:	goto yy401;
	}
yy436:
	yych = *++cursor;
	switch (yych) {
	case 't':	goto yy448;
	default:	goto yy401;
	}
yy437:
	yych = *++cursor;
	switch (yych) {
	case 't':	goto yy450;
	default:	goto yy401;
	}
yy438:
	yych = *++cursor;
	switch (yych) {
	case 'n':	goto yy451;
	default:	goto yy401;
	}
yy439:
	yych = *++cursor;
	switch (yych) {
	case 'u':	goto yy452;
	default:	goto yy401;
	}
yy440:
	yych = *++cursor;
	switch (yych) {
	case 'o':	goto yy453;
	default:	goto yy401;
	}
yy441:
	yych = *++cursor;
	switch (yych) {
	case 'b':	goto yy454;
	default:	goto yy401;
	}
yy442:
	++cursor;
#line 165 "../Source/raw_parser.h"
	{return pbrtParamType::Color; }
#line 2512 "<stdout>"
yy444:
	++cursor;
#line 158 "../Source/raw_parser.h"
	{return pbrtParamType::Float; }
#line 2517 "<stdout>"
yy446:
	yych = *++cursor;
	switch (yych) {
	case 'e':	goto yy455;
	default:	goto yy401;
	}
yy447:
	yych = *++cursor;
	switch (yych) {
	case 'l':	goto yy456;
	default:	goto yy401;
	}
yy448:
	++cursor;
#line 160 "../Source/raw_parser.h"
	{return pbrtParamType::Point; }
#line 2534 "<stdout>"
yy450:
	yych = *++cursor;
	switch (yych) {
	case 'r':	goto yy458;
	default:	goto yy401;
	}
yy451:
	yych = *++cursor;
	switch (yych) {
	case 'g':	goto yy459;
	default:	goto yy401;
	}
yy452:
	yych = *++cursor;
	switch (yych) {
	case 'r':	goto yy461;
	default:	goto yy401;
	}
yy453:
	yych = *++cursor;
	switch (yych) {
	case 'r':	goto yy462;
	default:	goto yy401;
	}
yy454:
	yych = *++cursor;
	switch (yych) {
	case 'o':	goto yy464;
	default:	goto yy401;
	}
yy455:
	yych = *++cursor;
	switch (yych) {
	case 'r':	goto yy465;
	default:	goto yy401;
	}
yy456:
	++cursor;
#line 162 "../Source/raw_parser.h"
	{return pbrtParamType::Normal; }
#line 2575 "<stdout>"
yy458:
	yych = *++cursor;
	switch (yych) {
	case 'u':	goto yy467;
	default:	goto yy401;
	}
yy459:
	++cursor;
#line 163 "../Source/raw_parser.h"
	{return pbrtParamType::String; }
#line 2586 "<stdout>"
yy461:
	yych = *++cursor;
	switch (yych) {
	case 'e':	goto yy468;
	default:	goto yy401;
	}
yy462:
	++cursor;
#line 161 "../Source/raw_parser.h"
	{return pbrtParamType::Vector; }
#line 2597 "<stdout>"
yy464:
	yych = *++cursor;
	switch (yych) {
	case 'd':	goto yy470;
	default:	goto yy401;
	}
yy465:
	++cursor;
#line 157 "../Source/raw_parser.h"
	{return pbrtParamType::Integer; }
#line 2608 "<stdout>"
yy467:
	yych = *++cursor;
	switch (yych) {
	case 'm':	goto yy471;
	default:	goto yy401;
	}
yy468:
	++cursor;
#line 168 "../Source/raw_parser.h"
	{return pbrtParamType::Texture; }
#line 2619 "<stdout>"
yy470:
	yych = *++cursor;
	switch (yych) {
	case 'y':	goto yy473;
	default:	goto yy401;
	}
yy471:
	++cursor;
#line 164 "../Source/raw_parser.h"
	{return pbrtParamType::Spectrum; }
#line 2630 "<stdout>"
yy473:
	++cursor;
#line 169 "../Source/raw_parser.h"
	{return pbrtParamType::Spectrum; }
#line 2635 "<stdout>"
}
#line 170 "../Source/raw_parser.h"

	return pbrtParamType::ERROR;
}

PbrtScene::ShapeType getShapeTypeFromString(const std::string& s)
{
	const char* cursor = &(*s.begin());
	const char* end = cursor + s.length();
	const char* marker = nullptr;
	
#line 2648 "<stdout>"
{
	char yych;
	yych = *cursor;
	switch (yych) {
	case 'c':	goto yy479;
	case 'd':	goto yy480;
	case 'h':	goto yy481;
	case 'l':	goto yy482;
	case 'n':	goto yy483;
	case 'p':	goto yy484;
	case 's':	goto yy485;
	case 't':	goto yy486;
	default:	goto yy477;
	}
yy477:
	++cursor;
yy478:
#line 185 "../Source/raw_parser.h"
	{return PbrtScene::ShapeType::ERROR;}
#line 2668 "<stdout>"
yy479:
	yych = *(marker = ++cursor);
	switch (yych) {
	case 'o':	goto yy487;
	case 'y':	goto yy489;
	default:	goto yy478;
	}
yy480:
	yych = *(marker = ++cursor);
	switch (yych) {
	case 'i':	goto yy490;
	default:	goto yy478;
	}
yy481:
	yych = *(marker = ++cursor);
	switch (yych) {
	case 'e':	goto yy491;
	case 'y':	goto yy492;
	default:	goto yy478;
	}
yy482:
	yych = *(marker = ++cursor);
	switch (yych) {
	case 'o':	goto yy493;
	default:	goto yy478;
	}
yy483:
	yych = *(marker = ++cursor);
	switch (yych) {
	case 'u':	goto yy494;
	default:	goto yy478;
	}
yy484:
	yych = *(marker = ++cursor);
	switch (yych) {
	case 'a':	goto yy495;
	case 'l':	goto yy496;
	default:	goto yy478;
	}
yy485:
	yych = *(marker = ++cursor);
	switch (yych) {
	case 'p':	goto yy497;
	default:	goto yy478;
	}
yy486:
	yych = *(marker = ++cursor);
	switch (yych) {
	case 'r':	goto yy498;
	default:	goto yy478;
	}
yy487:
	yych = *++cursor;
	switch (yych) {
	case 'n':	goto yy499;
	default:	goto yy488;
	}
yy488:
	cursor = marker;
	goto yy478;
yy489:
	yych = *++cursor;
	switch (yych) {
	case 'l':	goto yy500;
	default:	goto yy488;
	}
yy490:
	yych = *++cursor;
	switch (yych) {
	case 's':	goto yy501;
	default:	goto yy488;
	}
yy491:
	yych = *++cursor;
	switch (yych) {
	case 'i':	goto yy502;
	default:	goto yy488;
	}
yy492:
	yych = *++cursor;
	switch (yych) {
	case 'p':	goto yy503;
	default:	goto yy488;
	}
yy493:
	yych = *++cursor;
	switch (yych) {
	case 'o':	goto yy504;
	default:	goto yy488;
	}
yy494:
	yych = *++cursor;
	switch (yych) {
	case 'r':	goto yy505;
	default:	goto yy488;
	}
yy495:
	yych = *++cursor;
	switch (yych) {
	case 'r':	goto yy506;
	default:	goto yy488;
	}
yy496:
	yych = *++cursor;
	switch (yych) {
	case 'y':	goto yy507;
	default:	goto yy488;
	}
yy497:
	yych = *++cursor;
	switch (yych) {
	case 'h':	goto yy508;
	default:	goto yy488;
	}
yy498:
	yych = *++cursor;
	switch (yych) {
	case 'i':	goto yy509;
	default:	goto yy488;
	}
yy499:
	yych = *++cursor;
	switch (yych) {
	case 'e':	goto yy510;
	default:	goto yy488;
	}
yy500:
	yych = *++cursor;
	switch (yych) {
	case 'i':	goto yy512;
	default:	goto yy488;
	}
yy501:
	yych = *++cursor;
	switch (yych) {
	case 'k':	goto yy513;
	default:	goto yy488;
	}
yy502:
	yych = *++cursor;
	switch (yych) {
	case 'g':	goto yy515;
	default:	goto yy488;
	}
yy503:
	yych = *++cursor;
	switch (yych) {
	case 'e':	goto yy516;
	default:	goto yy488;
	}
yy504:
	yych = *++cursor;
	switch (yych) {
	case 'p':	goto yy517;
	default:	goto yy488;
	}
yy505:
	yych = *++cursor;
	switch (yych) {
	case 'b':	goto yy518;
	default:	goto yy488;
	}
yy506:
	yych = *++cursor;
	switch (yych) {
	case 'a':	goto yy519;
	default:	goto yy488;
	}
yy507:
	yych = *++cursor;
	switch (yych) {
	case 'm':	goto yy520;
	default:	goto yy488;
	}
yy508:
	yych = *++cursor;
	switch (yych) {
	case 'e':	goto yy521;
	default:	goto yy488;
	}
yy509:
	yych = *++cursor;
	switch (yych) {
	case 'a':	goto yy522;
	default:	goto yy488;
	}
yy510:
	++cursor;
#line 186 "../Source/raw_parser.h"
	{return PbrtScene::ShapeType::Cone; }
#line 2859 "<stdout>"
yy512:
	yych = *++cursor;
	switch (yych) {
	case 'n':	goto yy523;
	default:	goto yy488;
	}
yy513:
	++cursor;
#line 188 "../Source/raw_parser.h"
	{return PbrtScene::ShapeType::Disk; }
#line 2870 "<stdout>"
yy515:
	yych = *++cursor;
	switch (yych) {
	case 'h':	goto yy524;
	default:	goto yy488;
	}
yy516:
	yych = *++cursor;
	switch (yych) {
	case 'r':	goto yy525;
	default:	goto yy488;
	}
yy517:
	yych = *++cursor;
	switch (yych) {
	case 's':	goto yy526;
	default:	goto yy488;
	}
yy518:
	yych = *++cursor;
	switch (yych) {
	case 's':	goto yy527;
	default:	goto yy488;
	}
yy519:
	yych = *++cursor;
	switch (yych) {
	case 'b':	goto yy529;
	default:	goto yy488;
	}
yy520:
	yych = *++cursor;
	switch (yych) {
	case 'e':	goto yy530;
	default:	goto yy488;
	}
yy521:
	yych = *++cursor;
	switch (yych) {
	case 'r':	goto yy531;
	default:	goto yy488;
	}
yy522:
	yych = *++cursor;
	switch (yych) {
	case 'n':	goto yy532;
	default:	goto yy488;
	}
yy523:
	yych = *++cursor;
	switch (yych) {
	case 'd':	goto yy533;
	default:	goto yy488;
	}
yy524:
	yych = *++cursor;
	switch (yych) {
	case 't':	goto yy534;
	default:	goto yy488;
	}
yy525:
	yych = *++cursor;
	switch (yych) {
	case 'b':	goto yy535;
	default:	goto yy488;
	}
yy526:
	yych = *++cursor;
	switch (yych) {
	case 'u':	goto yy536;
	default:	goto yy488;
	}
yy527:
	++cursor;
#line 192 "../Source/raw_parser.h"
	{return PbrtScene::ShapeType::Nurbs; }
#line 2947 "<stdout>"
yy529:
	yych = *++cursor;
	switch (yych) {
	case 'o':	goto yy537;
	default:	goto yy488;
	}
yy530:
	yych = *++cursor;
	switch (yych) {
	case 's':	goto yy538;
	default:	goto yy488;
	}
yy531:
	yych = *++cursor;
	switch (yych) {
	case 'e':	goto yy539;
	default:	goto yy488;
	}
yy532:
	yych = *++cursor;
	switch (yych) {
	case 'g':	goto yy541;
	default:	goto yy488;
	}
yy533:
	yych = *++cursor;
	switch (yych) {
	case 'e':	goto yy542;
	default:	goto yy488;
	}
yy534:
	yych = *++cursor;
	switch (yych) {
	case 'f':	goto yy543;
	default:	goto yy488;
	}
yy535:
	yych = *++cursor;
	switch (yych) {
	case 'o':	goto yy544;
	default:	goto yy488;
	}
yy536:
	yych = *++cursor;
	switch (yych) {
	case 'b':	goto yy545;
	default:	goto yy488;
	}
yy537:
	yych = *++cursor;
	switch (yych) {
	case 'l':	goto yy546;
	default:	goto yy488;
	}
yy538:
	yych = *++cursor;
	switch (yych) {
	case 'h':	goto yy547;
	default:	goto yy488;
	}
yy539:
	++cursor;
#line 194 "../Source/raw_parser.h"
	{return PbrtScene::ShapeType::Sphere; }
#line 3012 "<stdout>"
yy541:
	yych = *++cursor;
	switch (yych) {
	case 'l':	goto yy549;
	default:	goto yy488;
	}
yy542:
	yych = *++cursor;
	switch (yych) {
	case 'r':	goto yy550;
	default:	goto yy488;
	}
yy543:
	yych = *++cursor;
	switch (yych) {
	case 'i':	goto yy552;
	default:	goto yy488;
	}
yy544:
	yych = *++cursor;
	switch (yych) {
	case 'l':	goto yy553;
	default:	goto yy488;
	}
yy545:
	yych = *++cursor;
	switch (yych) {
	case 'd':	goto yy554;
	default:	goto yy488;
	}
yy546:
	yych = *++cursor;
	switch (yych) {
	case 'o':	goto yy555;
	default:	goto yy488;
	}
yy547:
	++cursor;
#line 196 "../Source/raw_parser.h"
	{return PbrtScene::ShapeType::Plymesh; }
#line 3053 "<stdout>"
yy549:
	yych = *++cursor;
	switch (yych) {
	case 'e':	goto yy556;
	default:	goto yy488;
	}
yy550:
	++cursor;
#line 187 "../Source/raw_parser.h"
	{return PbrtScene::ShapeType::Cylinder; }
#line 3064 "<stdout>"
yy552:
	yych = *++cursor;
	switch (yych) {
	case 'e':	goto yy557;
	default:	goto yy488;
	}
yy553:
	yych = *++cursor;
	switch (yych) {
	case 'o':	goto yy558;
	default:	goto yy488;
	}
yy554:
	yych = *++cursor;
	switch (yych) {
	case 'i':	goto yy559;
	default:	goto yy488;
	}
yy555:
	yych = *++cursor;
	switch (yych) {
	case 'i':	goto yy560;
	default:	goto yy488;
	}
yy556:
	yych = *++cursor;
	switch (yych) {
	case 'm':	goto yy561;
	default:	goto yy488;
	}
yy557:
	yych = *++cursor;
	switch (yych) {
	case 'l':	goto yy562;
	default:	goto yy488;
	}
yy558:
	yych = *++cursor;
	switch (yych) {
	case 'i':	goto yy563;
	default:	goto yy488;
	}
yy559:
	yych = *++cursor;
	switch (yych) {
	case 'v':	goto yy564;
	default:	goto yy488;
	}
yy560:
	yych = *++cursor;
	switch (yych) {
	case 'd':	goto yy566;
	default:	goto yy488;
	}
yy561:
	yych = *++cursor;
	switch (yych) {
	case 'e':	goto yy568;
	default:	goto yy488;
	}
yy562:
	yych = *++cursor;
	switch (yych) {
	case 'd':	goto yy569;
	default:	goto yy488;
	}
yy563:
	yych = *++cursor;
	switch (yych) {
	case 'd':	goto yy571;
	default:	goto yy488;
	}
yy564:
	++cursor;
#line 191 "../Source/raw_parser.h"
	{return PbrtScene::ShapeType::Loopsubdiv; }
#line 3141 "<stdout>"
yy566:
	++cursor;
#line 193 "../Source/raw_parser.h"
	{return PbrtScene::ShapeType::Paraboloid; }
#line 3146 "<stdout>"
yy568:
	yych = *++cursor;
	switch (yych) {
	case 's':	goto yy573;
	default:	goto yy488;
	}
yy569:
	++cursor;
#line 190 "../Source/raw_parser.h"
	{return PbrtScene::ShapeType::Heightfield; }
#line 3157 "<stdout>"
yy571:
	++cursor;
#line 189 "../Source/raw_parser.h"
	{return PbrtScene::ShapeType::Hyperboloid; }
#line 3162 "<stdout>"
yy573:
	yych = *++cursor;
	switch (yych) {
	case 'h':	goto yy574;
	default:	goto yy488;
	}
yy574:
	++cursor;
#line 195 "../Source/raw_parser.h"
	{return PbrtScene::ShapeType::Trianglemesh; }
#line 3173 "<stdout>"
}
#line 197 "../Source/raw_parser.h"

	return PbrtScene::ShapeType::ERROR;
}

Light::Type getLightTypeFromString(const std::string& s)
{
	const char* cursor = &(*s.begin());
	const char* end = cursor + s.length();
	const char* marker = nullptr;
	
#line 3186 "<stdout>"
{
	char yych;
	yych = *cursor;
	switch (yych) {
	case 'd':	goto yy580;
	case 'g':	goto yy581;
	case 'i':	goto yy582;
	case 'p':	goto yy583;
	case 's':	goto yy584;
	default:	goto yy578;
	}
yy578:
	++cursor;
yy579:
#line 212 "../Source/raw_parser.h"
	{return Light::Type::ERROR;}
#line 3203 "<stdout>"
yy580:
	yych = *(marker = ++cursor);
	switch (yych) {
	case 'i':	goto yy585;
	default:	goto yy579;
	}
yy581:
	yych = *(marker = ++cursor);
	switch (yych) {
	case 'o':	goto yy587;
	default:	goto yy579;
	}
yy582:
	yych = *(marker = ++cursor);
	switch (yych) {
	case 'n':	goto yy588;
	default:	goto yy579;
	}
yy583:
	yych = *(marker = ++cursor);
	switch (yych) {
	case 'o':	goto yy589;
	case 'r':	goto yy590;
	default:	goto yy579;
	}
yy584:
	yych = *(marker = ++cursor);
	switch (yych) {
	case 'p':	goto yy591;
	default:	goto yy579;
	}
yy585:
	yych = *++cursor;
	switch (yych) {
	case 's':	goto yy592;
	default:	goto yy586;
	}
yy586:
	cursor = marker;
	goto yy579;
yy587:
	yych = *++cursor;
	switch (yych) {
	case 'n':	goto yy593;
	default:	goto yy586;
	}
yy588:
	yych = *++cursor;
	switch (yych) {
	case 'f':	goto yy594;
	default:	goto yy586;
	}
yy589:
	yych = *++cursor;
	switch (yych) {
	case 'i':	goto yy595;
	default:	goto yy586;
	}
yy590:
	yych = *++cursor;
	switch (yych) {
	case 'o':	goto yy596;
	default:	goto yy586;
	}
yy591:
	yych = *++cursor;
	switch (yych) {
	case 'o':	goto yy597;
	default:	goto yy586;
	}
yy592:
	yych = *++cursor;
	switch (yych) {
	case 't':	goto yy598;
	default:	goto yy586;
	}
yy593:
	yych = *++cursor;
	switch (yych) {
	case 'i':	goto yy599;
	default:	goto yy586;
	}
yy594:
	yych = *++cursor;
	switch (yych) {
	case 'i':	goto yy600;
	default:	goto yy586;
	}
yy595:
	yych = *++cursor;
	switch (yych) {
	case 'n':	goto yy601;
	default:	goto yy586;
	}
yy596:
	yych = *++cursor;
	switch (yych) {
	case 'j':	goto yy602;
	default:	goto yy586;
	}
yy597:
	yych = *++cursor;
	switch (yych) {
	case 't':	goto yy603;
	default:	goto yy586;
	}
yy598:
	yych = *++cursor;
	switch (yych) {
	case 'a':	goto yy605;
	default:	goto yy586;
	}
yy599:
	yych = *++cursor;
	switch (yych) {
	case 'o':	goto yy606;
	default:	goto yy586;
	}
yy600:
	yych = *++cursor;
	switch (yych) {
	case 'n':	goto yy607;
	default:	goto yy586;
	}
yy601:
	yych = *++cursor;
	switch (yych) {
	case 't':	goto yy608;
	default:	goto yy586;
	}
yy602:
	yych = *++cursor;
	switch (yych) {
	case 'e':	goto yy610;
	default:	goto yy586;
	}
yy603:
	++cursor;
#line 218 "../Source/raw_parser.h"
	{return Light::Type::Spot; }
#line 3344 "<stdout>"
yy605:
	yych = *++cursor;
	switch (yych) {
	case 'n':	goto yy611;
	default:	goto yy586;
	}
yy606:
	yych = *++cursor;
	switch (yych) {
	case 'm':	goto yy612;
	default:	goto yy586;
	}
yy607:
	yych = *++cursor;
	switch (yych) {
	case 'i':	goto yy613;
	default:	goto yy586;
	}
yy608:
	++cursor;
#line 216 "../Source/raw_parser.h"
	{return Light::Type::Point; }
#line 3367 "<stdout>"
yy610:
	yych = *++cursor;
	switch (yych) {
	case 'c':	goto yy614;
	default:	goto yy586;
	}
yy611:
	yych = *++cursor;
	switch (yych) {
	case 't':	goto yy615;
	default:	goto yy586;
	}
yy612:
	yych = *++cursor;
	switch (yych) {
	case 'e':	goto yy617;
	default:	goto yy586;
	}
yy613:
	yych = *++cursor;
	switch (yych) {
	case 't':	goto yy618;
	default:	goto yy586;
	}
yy614:
	yych = *++cursor;
	switch (yych) {
	case 't':	goto yy619;
	default:	goto yy586;
	}
yy615:
	++cursor;
#line 213 "../Source/raw_parser.h"
	{return Light::Type::Distant; }
#line 3402 "<stdout>"
yy617:
	yych = *++cursor;
	switch (yych) {
	case 't':	goto yy620;
	default:	goto yy586;
	}
yy618:
	yych = *++cursor;
	switch (yych) {
	case 'e':	goto yy621;
	default:	goto yy586;
	}
yy619:
	yych = *++cursor;
	switch (yych) {
	case 'i':	goto yy623;
	default:	goto yy586;
	}
yy620:
	yych = *++cursor;
	switch (yych) {
	case 'r':	goto yy624;
	default:	goto yy586;
	}
yy621:
	++cursor;
#line 215 "../Source/raw_parser.h"
	{return Light::Type::Infinite; }
#line 3431 "<stdout>"
yy623:
	yych = *++cursor;
	switch (yych) {
	case 'o':	goto yy625;
	default:	goto yy586;
	}
yy624:
	yych = *++cursor;
	switch (yych) {
	case 'i':	goto yy626;
	default:	goto yy586;
	}
yy625:
	yych = *++cursor;
	switch (yych) {
	case 'n':	goto yy627;
	default:	goto yy586;
	}
yy626:
	yych = *++cursor;
	switch (yych) {
	case 'c':	goto yy629;
	default:	goto yy586;
	}
yy627:
	++cursor;
#line 217 "../Source/raw_parser.h"
	{return Light::Type::Projection; }
#line 3460 "<stdout>"
yy629:
	++cursor;
#line 214 "../Source/raw_parser.h"
	{return Light::Type::Goniometric; }
#line 3465 "<stdout>"
}
#line 219 "../Source/raw_parser.h"

	return Light::Type::ERROR;
}

Material::Type getMaterialTypeFromString(const std::string& s)
{
	if (s.length() == 0)
		return Material::None;

	const char* cursor = &(*s.begin());
	const char* end = cursor + s.length();
	const char* marker = nullptr;
	
#line 3481 "<stdout>"
{
	char yych;
	yych = *cursor;
	switch (yych) {
	case 'f':	goto yy635;
	case 'g':	goto yy636;
	case 'h':	goto yy637;
	case 'k':	goto yy638;
	case 'm':	goto yy639;
	case 'p':	goto yy640;
	case 's':	goto yy641;
	case 't':	goto yy642;
	case 'u':	goto yy643;
	default:	goto yy633;
	}
yy633:
	++cursor;
yy634:
#line 237 "../Source/raw_parser.h"
	{return Material::Type::ERROR;}
#line 3502 "<stdout>"
yy635:
	yych = *(marker = ++cursor);
	switch (yych) {
	case 'o':	goto yy644;
	default:	goto yy634;
	}
yy636:
	yych = *(marker = ++cursor);
	switch (yych) {
	case 'l':	goto yy646;
	default:	goto yy634;
	}
yy637:
	yych = *(marker = ++cursor);
	switch (yych) {
	case 'a':	goto yy647;
	default:	goto yy634;
	}
yy638:
	yych = *(marker = ++cursor);
	switch (yych) {
	case 'd':	goto yy648;
	default:	goto yy634;
	}
yy639:
	yych = *(marker = ++cursor);
	switch (yych) {
	case 'a':	goto yy649;
	case 'e':	goto yy650;
	case 'i':	goto yy651;
	default:	goto yy634;
	}
yy640:
	yych = *(marker = ++cursor);
	switch (yych) {
	case 'l':	goto yy652;
	default:	goto yy634;
	}
yy641:
	yych = *(marker = ++cursor);
	switch (yych) {
	case 'h':	goto yy653;
	case 'u':	goto yy654;
	default:	goto yy634;
	}
yy642:
	yych = *(marker = ++cursor);
	switch (yych) {
	case 'r':	goto yy655;
	default:	goto yy634;
	}
yy643:
	yych = *(marker = ++cursor);
	switch (yych) {
	case 'b':	goto yy656;
	default:	goto yy634;
	}
yy644:
	yych = *++cursor;
	switch (yych) {
	case 'u':	goto yy657;
	default:	goto yy645;
	}
yy645:
	cursor = marker;
	goto yy634;
yy646:
	yych = *++cursor;
	switch (yych) {
	case 'a':	goto yy658;
	default:	goto yy645;
	}
yy647:
	yych = *++cursor;
	switch (yych) {
	case 'i':	goto yy659;
	default:	goto yy645;
	}
yy648:
	yych = *++cursor;
	switch (yych) {
	case 's':	goto yy660;
	default:	goto yy645;
	}
yy649:
	yych = *++cursor;
	switch (yych) {
	case 't':	goto yy661;
	default:	goto yy645;
	}
yy650:
	yych = *++cursor;
	switch (yych) {
	case 'a':	goto yy662;
	case 't':	goto yy663;
	default:	goto yy645;
	}
yy651:
	yych = *++cursor;
	switch (yych) {
	case 'r':	goto yy664;
	case 'x':	goto yy665;
	default:	goto yy645;
	}
yy652:
	yych = *++cursor;
	switch (yych) {
	case 'a':	goto yy667;
	default:	goto yy645;
	}
yy653:
	yych = *++cursor;
	switch (yych) {
	case 'i':	goto yy668;
	default:	goto yy645;
	}
yy654:
	yych = *++cursor;
	switch (yych) {
	case 'b':	goto yy669;
	default:	goto yy645;
	}
yy655:
	yych = *++cursor;
	switch (yych) {
	case 'a':	goto yy670;
	default:	goto yy645;
	}
yy656:
	yych = *++cursor;
	switch (yych) {
	case 'e':	goto yy671;
	default:	goto yy645;
	}
yy657:
	yych = *++cursor;
	switch (yych) {
	case 'r':	goto yy672;
	default:	goto yy645;
	}
yy658:
	yych = *++cursor;
	switch (yych) {
	case 's':	goto yy673;
	default:	goto yy645;
	}
yy659:
	yych = *++cursor;
	switch (yych) {
	case 'r':	goto yy674;
	default:	goto yy645;
	}
yy660:
	yych = *++cursor;
	switch (yych) {
	case 'u':	goto yy676;
	default:	goto yy645;
	}
yy661:
	yych = *++cursor;
	switch (yych) {
	case 't':	goto yy677;
	default:	goto yy645;
	}
yy662:
	yych = *++cursor;
	switch (yych) {
	case 's':	goto yy678;
	default:	goto yy645;
	}
yy663:
	yych = *++cursor;
	switch (yych) {
	case 'a':	goto yy679;
	default:	goto yy645;
	}
yy664:
	yych = *++cursor;
	switch (yych) {
	case 'r':	goto yy680;
	default:	goto yy645;
	}
yy665:
	++cursor;
#line 244 "../Source/raw_parser.h"
	{return Material::Type::Mix; }
#line 3689 "<stdout>"
yy667:
	yych = *++cursor;
	switch (yych) {
	case 's':	goto yy681;
	default:	goto yy645;
	}
yy668:
	yych = *++cursor;
	switch (yych) {
	case 'n':	goto yy682;
	default:	goto yy645;
	}
yy669:
	yych = *++cursor;
	switch (yych) {
	case 's':	goto yy683;
	default:	goto yy645;
	}
yy670:
	yych = *++cursor;
	switch (yych) {
	case 'n':	goto yy684;
	default:	goto yy645;
	}
yy671:
	yych = *++cursor;
	switch (yych) {
	case 'r':	goto yy685;
	default:	goto yy645;
	}
yy672:
	yych = *++cursor;
	switch (yych) {
	case 'i':	goto yy687;
	default:	goto yy645;
	}
yy673:
	yych = *++cursor;
	switch (yych) {
	case 's':	goto yy688;
	default:	goto yy645;
	}
yy674:
	++cursor;
#line 251 "../Source/raw_parser.h"
	{return Material::Type::Hair; }
#line 3736 "<stdout>"
yy676:
	yych = *++cursor;
	switch (yych) {
	case 'b':	goto yy690;
	default:	goto yy645;
	}
yy677:
	yych = *++cursor;
	switch (yych) {
	case 'e':	goto yy691;
	default:	goto yy645;
	}
yy678:
	yych = *++cursor;
	switch (yych) {
	case 'u':	goto yy693;
	default:	goto yy645;
	}
yy679:
	yych = *++cursor;
	switch (yych) {
	case 'l':	goto yy694;
	default:	goto yy645;
	}
yy680:
	yych = *++cursor;
	switch (yych) {
	case 'o':	goto yy696;
	default:	goto yy645;
	}
yy681:
	yych = *++cursor;
	switch (yych) {
	case 't':	goto yy697;
	default:	goto yy645;
	}
yy682:
	yych = *++cursor;
	switch (yych) {
	case 'y':	goto yy698;
	default:	goto yy645;
	}
yy683:
	yych = *++cursor;
	switch (yych) {
	case 't':	goto yy699;
	case 'u':	goto yy700;
	default:	goto yy645;
	}
yy684:
	yych = *++cursor;
	switch (yych) {
	case 's':	goto yy701;
	default:	goto yy645;
	}
yy685:
	++cursor;
#line 250 "../Source/raw_parser.h"
	{return Material::Type::Uber; }
#line 3796 "<stdout>"
yy687:
	yych = *++cursor;
	switch (yych) {
	case 'e':	goto yy702;
	default:	goto yy645;
	}
yy688:
	++cursor;
#line 238 "../Source/raw_parser.h"
	{return Material::Type::Glass; }
#line 3807 "<stdout>"
yy690:
	yych = *++cursor;
	switch (yych) {
	case 's':	goto yy703;
	default:	goto yy645;
	}
yy691:
	++cursor;
#line 240 "../Source/raw_parser.h"
	{return Material::Type::Matte; }
#line 3818 "<stdout>"
yy693:
	yych = *++cursor;
	switch (yych) {
	case 'r':	goto yy704;
	default:	goto yy645;
	}
yy694:
	++cursor;
#line 242 "../Source/raw_parser.h"
	{return Material::Type::Metal; }
#line 3829 "<stdout>"
yy696:
	yych = *++cursor;
	switch (yych) {
	case 'r':	goto yy705;
	default:	goto yy645;
	}
yy697:
	yych = *++cursor;
	switch (yych) {
	case 'i':	goto yy707;
	default:	goto yy645;
	}
yy698:
	yych = *++cursor;
	switch (yych) {
	case 'm':	goto yy708;
	default:	goto yy645;
	}
yy699:
	yych = *++cursor;
	switch (yych) {
	case 'r':	goto yy709;
	default:	goto yy645;
	}
yy700:
	yych = *++cursor;
	switch (yych) {
	case 'r':	goto yy710;
	default:	goto yy645;
	}
yy701:
	yych = *++cursor;
	switch (yych) {
	case 'l':	goto yy711;
	default:	goto yy645;
	}
yy702:
	yych = *++cursor;
	switch (yych) {
	case 'r':	goto yy712;
	default:	goto yy645;
	}
yy703:
	yych = *++cursor;
	switch (yych) {
	case 'u':	goto yy714;
	default:	goto yy645;
	}
yy704:
	yych = *++cursor;
	switch (yych) {
	case 'e':	goto yy715;
	default:	goto yy645;
	}
yy705:
	++cursor;
#line 243 "../Source/raw_parser.h"
	{return Material::Type::Mirror; }
#line 3888 "<stdout>"
yy707:
	yych = *++cursor;
	switch (yych) {
	case 'c':	goto yy716;
	default:	goto yy645;
	}
yy708:
	yych = *++cursor;
	switch (yych) {
	case 'e':	goto yy718;
	default:	goto yy645;
	}
yy709:
	yych = *++cursor;
	switch (yych) {
	case 'a':	goto yy719;
	default:	goto yy645;
	}
yy710:
	yych = *++cursor;
	switch (yych) {
	case 'f':	goto yy720;
	default:	goto yy645;
	}
yy711:
	yych = *++cursor;
	switch (yych) {
	case 'u':	goto yy721;
	default:	goto yy645;
	}
yy712:
	++cursor;
#line 252 "../Source/raw_parser.h"
	{return Material::Type::Fourier; }
#line 3923 "<stdout>"
yy714:
	yych = *++cursor;
	switch (yych) {
	case 'r':	goto yy722;
	default:	goto yy645;
	}
yy715:
	yych = *++cursor;
	switch (yych) {
	case 'd':	goto yy723;
	default:	goto yy645;
	}
yy716:
	++cursor;
#line 245 "../Source/raw_parser.h"
	{return Material::Type::Plastic; }
#line 3940 "<stdout>"
yy718:
	yych = *++cursor;
	switch (yych) {
	case 't':	goto yy725;
	default:	goto yy645;
	}
yy719:
	yych = *++cursor;
	switch (yych) {
	case 't':	goto yy726;
	default:	goto yy645;
	}
yy720:
	yych = *++cursor;
	switch (yych) {
	case 'a':	goto yy727;
	default:	goto yy645;
	}
yy721:
	yych = *++cursor;
	switch (yych) {
	case 'c':	goto yy728;
	default:	goto yy645;
	}
yy722:
	yych = *++cursor;
	switch (yych) {
	case 'f':	goto yy729;
	default:	goto yy645;
	}
yy723:
	++cursor;
#line 241 "../Source/raw_parser.h"
	{return Material::Type::Measured; }
#line 3975 "<stdout>"
yy725:
	yych = *++cursor;
	switch (yych) {
	case 'a':	goto yy730;
	default:	goto yy645;
	}
yy726:
	yych = *++cursor;
	switch (yych) {
	case 'e':	goto yy731;
	default:	goto yy645;
	}
yy727:
	yych = *++cursor;
	switch (yych) {
	case 'c':	goto yy733;
	default:	goto yy645;
	}
yy728:
	yych = *++cursor;
	switch (yych) {
	case 'e':	goto yy734;
	default:	goto yy645;
	}
yy729:
	yych = *++cursor;
	switch (yych) {
	case 'a':	goto yy735;
	default:	goto yy645;
	}
yy730:
	yych = *++cursor;
	switch (yych) {
	case 'l':	goto yy736;
	default:	goto yy645;
	}
yy731:
	++cursor;
#line 247 "../Source/raw_parser.h"
	{return Material::Type::Substrate; }
#line 4016 "<stdout>"
yy733:
	yych = *++cursor;
	switch (yych) {
	case 'e':	goto yy738;
	default:	goto yy645;
	}
yy734:
	yych = *++cursor;
	switch (yych) {
	case 'n':	goto yy740;
	default:	goto yy645;
	}
yy735:
	yych = *++cursor;
	switch (yych) {
	case 'c':	goto yy741;
	default:	goto yy645;
	}
yy736:
	++cursor;
#line 246 "../Source/raw_parser.h"
	{return Material::Type::Shinymetal; }
#line 4039 "<stdout>"
yy738:
	++cursor;
#line 248 "../Source/raw_parser.h"
	{return Material::Type::Subsurface; }
#line 4044 "<stdout>"
yy740:
	yych = *++cursor;
	switch (yych) {
	case 't':	goto yy742;
	default:	goto yy645;
	}
yy741:
	yych = *++cursor;
	switch (yych) {
	case 'e':	goto yy744;
	default:	goto yy645;
	}
yy742:
	++cursor;
#line 249 "../Source/raw_parser.h"
	{return Material::Type::Translucent; }
#line 4061 "<stdout>"
yy744:
	++cursor;
#line 239 "../Source/raw_parser.h"
	{return Material::Type::Kdsubsurface; }
#line 4066 "<stdout>"
}
#line 253 "../Source/raw_parser.h"

	return Material::Type::ERROR;
}

size_t getTextureTypeFromString(const std::string& s)
{
	const char* cursor = &(*s.begin());
	const char* end = cursor + s.length();
	const char* marker = nullptr;
	
#line 4079 "<stdout>"
{
	char yych;
	yych = *cursor;
	switch (yych) {
	case 'b':	goto yy750;
	case 'c':	goto yy751;
	case 'd':	goto yy752;
	case 'f':	goto yy753;
	case 'i':	goto yy754;
	case 'm':	goto yy755;
	case 's':	goto yy756;
	case 'u':	goto yy757;
	case 'w':	goto yy758;
	default:	goto yy748;
	}
yy748:
	++cursor;
yy749:
#line 268 "../Source/raw_parser.h"
	{return Texture<int>::Type::ERROR;}
#line 4100 "<stdout>"
yy750:
	yych = *(marker = ++cursor);
	switch (yych) {
	case 'i':	goto yy759;
	default:	goto yy749;
	}
yy751:
	yych = *(marker = ++cursor);
	switch (yych) {
	case 'h':	goto yy761;
	case 'o':	goto yy762;
	default:	goto yy749;
	}
yy752:
	yych = *(marker = ++cursor);
	switch (yych) {
	case 'o':	goto yy763;
	default:	goto yy749;
	}
yy753:
	yych = *(marker = ++cursor);
	switch (yych) {
	case 'b':	goto yy764;
	default:	goto yy749;
	}
yy754:
	yych = *(marker = ++cursor);
	switch (yych) {
	case 'm':	goto yy765;
	default:	goto yy749;
	}
yy755:
	yych = *(marker = ++cursor);
	switch (yych) {
	case 'a':	goto yy766;
	case 'i':	goto yy767;
	default:	goto yy749;
	}
yy756:
	yych = *(marker = ++cursor);
	switch (yych) {
	case 'c':	goto yy768;
	default:	goto yy749;
	}
yy757:
	yych = *++cursor;
	switch (yych) {
	case 'v':	goto yy769;
	default:	goto yy749;
	}
yy758:
	yych = *(marker = ++cursor);
	switch (yych) {
	case 'i':	goto yy771;
	case 'r':	goto yy772;
	default:	goto yy749;
	}
yy759:
	yych = *++cursor;
	switch (yych) {
	case 'l':	goto yy773;
	default:	goto yy760;
	}
yy760:
	cursor = marker;
	goto yy749;
yy761:
	yych = *++cursor;
	switch (yych) {
	case 'e':	goto yy774;
	default:	goto yy760;
	}
yy762:
	yych = *++cursor;
	switch (yych) {
	case 'n':	goto yy775;
	default:	goto yy760;
	}
yy763:
	yych = *++cursor;
	switch (yych) {
	case 't':	goto yy776;
	default:	goto yy760;
	}
yy764:
	yych = *++cursor;
	switch (yych) {
	case 'm':	goto yy777;
	default:	goto yy760;
	}
yy765:
	yych = *++cursor;
	switch (yych) {
	case 'a':	goto yy779;
	default:	goto yy760;
	}
yy766:
	yych = *++cursor;
	switch (yych) {
	case 'r':	goto yy780;
	default:	goto yy760;
	}
yy767:
	yych = *++cursor;
	switch (yych) {
	case 'x':	goto yy781;
	default:	goto yy760;
	}
yy768:
	yych = *++cursor;
	switch (yych) {
	case 'a':	goto yy783;
	default:	goto yy760;
	}
yy769:
	++cursor;
#line 278 "../Source/raw_parser.h"
	{return Texture<int>::Type::Uv; }
#line 4219 "<stdout>"
yy771:
	yych = *++cursor;
	switch (yych) {
	case 'n':	goto yy784;
	default:	goto yy760;
	}
yy772:
	yych = *++cursor;
	switch (yych) {
	case 'i':	goto yy785;
	default:	goto yy760;
	}
yy773:
	yych = *++cursor;
	switch (yych) {
	case 'e':	goto yy786;
	default:	goto yy760;
	}
yy774:
	yych = *++cursor;
	switch (yych) {
	case 'c':	goto yy787;
	default:	goto yy760;
	}
yy775:
	yych = *++cursor;
	switch (yych) {
	case 's':	goto yy788;
	default:	goto yy760;
	}
yy776:
	yych = *++cursor;
	switch (yych) {
	case 's':	goto yy789;
	default:	goto yy760;
	}
yy777:
	++cursor;
#line 273 "../Source/raw_parser.h"
	{return Texture<int>::Type::Fbm; }
#line 4260 "<stdout>"
yy779:
	yych = *++cursor;
	switch (yych) {
	case 'g':	goto yy791;
	default:	goto yy760;
	}
yy780:
	yych = *++cursor;
	switch (yych) {
	case 'b':	goto yy792;
	default:	goto yy760;
	}
yy781:
	++cursor;
#line 276 "../Source/raw_parser.h"
	{return Texture<int>::Type::Mix; }
#line 4277 "<stdout>"
yy783:
	yych = *++cursor;
	switch (yych) {
	case 'l':	goto yy793;
	default:	goto yy760;
	}
yy784:
	yych = *++cursor;
	switch (yych) {
	case 'd':	goto yy794;
	default:	goto yy760;
	}
yy785:
	yych = *++cursor;
	switch (yych) {
	case 'n':	goto yy795;
	default:	goto yy760;
	}
yy786:
	yych = *++cursor;
	switch (yych) {
	case 'r':	goto yy796;
	default:	goto yy760;
	}
yy787:
	yych = *++cursor;
	switch (yych) {
	case 'k':	goto yy797;
	default:	goto yy760;
	}
yy788:
	yych = *++cursor;
	switch (yych) {
	case 't':	goto yy798;
	default:	goto yy760;
	}
yy789:
	++cursor;
#line 272 "../Source/raw_parser.h"
	{return Texture<int>::Type::Dots; }
#line 4318 "<stdout>"
yy791:
	yych = *++cursor;
	switch (yych) {
	case 'e':	goto yy799;
	default:	goto yy760;
	}
yy792:
	yych = *++cursor;
	switch (yych) {
	case 'l':	goto yy800;
	default:	goto yy760;
	}
yy793:
	yych = *++cursor;
	switch (yych) {
	case 'e':	goto yy801;
	default:	goto yy760;
	}
yy794:
	yych = *++cursor;
	switch (yych) {
	case 'y':	goto yy803;
	default:	goto yy760;
	}
yy795:
	yych = *++cursor;
	switch (yych) {
	case 'k':	goto yy805;
	default:	goto yy760;
	}
yy796:
	yych = *++cursor;
	switch (yych) {
	case 'p':	goto yy806;
	default:	goto yy760;
	}
yy797:
	yych = *++cursor;
	switch (yych) {
	case 'e':	goto yy808;
	default:	goto yy760;
	}
yy798:
	yych = *++cursor;
	switch (yych) {
	case 'a':	goto yy809;
	default:	goto yy760;
	}
yy799:
	yych = *++cursor;
	switch (yych) {
	case 'm':	goto yy810;
	default:	goto yy760;
	}
yy800:
	yych = *++cursor;
	switch (yych) {
	case 'e':	goto yy811;
	default:	goto yy760;
	}
yy801:
	++cursor;
#line 277 "../Source/raw_parser.h"
	{return Texture<int>::Type::Scale; }
#line 4383 "<stdout>"
yy803:
	++cursor;
#line 279 "../Source/raw_parser.h"
	{return Texture<int>::Type::Windy; }
#line 4388 "<stdout>"
yy805:
	yych = *++cursor;
	switch (yych) {
	case 'l':	goto yy813;
	default:	goto yy760;
	}
yy806:
	++cursor;
#line 269 "../Source/raw_parser.h"
	{return Texture<int>::Type::Bilerp; }
#line 4399 "<stdout>"
yy808:
	yych = *++cursor;
	switch (yych) {
	case 'r':	goto yy814;
	default:	goto yy760;
	}
yy809:
	yych = *++cursor;
	switch (yych) {
	case 'n':	goto yy815;
	default:	goto yy760;
	}
yy810:
	yych = *++cursor;
	switch (yych) {
	case 'a':	goto yy816;
	default:	goto yy760;
	}
yy811:
	++cursor;
#line 275 "../Source/raw_parser.h"
	{return Texture<int>::Type::Marble; }
#line 4422 "<stdout>"
yy813:
	yych = *++cursor;
	switch (yych) {
	case 'e':	goto yy817;
	default:	goto yy760;
	}
yy814:
	yych = *++cursor;
	switch (yych) {
	case 'b':	goto yy818;
	default:	goto yy760;
	}
yy815:
	yych = *++cursor;
	switch (yych) {
	case 't':	goto yy819;
	default:	goto yy760;
	}
yy816:
	yych = *++cursor;
	switch (yych) {
	case 'p':	goto yy821;
	default:	goto yy760;
	}
yy817:
	yych = *++cursor;
	switch (yych) {
	case 'd':	goto yy823;
	default:	goto yy760;
	}
yy818:
	yych = *++cursor;
	switch (yych) {
	case 'o':	goto yy825;
	default:	goto yy760;
	}
yy819:
	++cursor;
#line 271 "../Source/raw_parser.h"
	{return Texture<int>::Type::Constant; }
#line 4463 "<stdout>"
yy821:
	++cursor;
#line 274 "../Source/raw_parser.h"
	{return Texture<int>::Type::Imagemap; }
#line 4468 "<stdout>"
yy823:
	++cursor;
#line 280 "../Source/raw_parser.h"
	{return Texture<int>::Type::Wrinkled; }
#line 4473 "<stdout>"
yy825:
	yych = *++cursor;
	switch (yych) {
	case 'a':	goto yy826;
	default:	goto yy760;
	}
yy826:
	yych = *++cursor;
	switch (yych) {
	case 'r':	goto yy827;
	default:	goto yy760;
	}
yy827:
	yych = *++cursor;
	switch (yych) {
	case 'd':	goto yy828;
	default:	goto yy760;
	}
yy828:
	++cursor;
#line 270 "../Source/raw_parser.h"
	{return Texture<int>::Type::Checkerboard; }
#line 4496 "<stdout>"
}
#line 281 "../Source/raw_parser.h"

	return Texture<int>::ERROR;
}